### ISSUE TITLE
StsAssumeRoleCredentialsProvider is missing sourceId and policy, preventing scoped down policies

### ISSUE THREAD

**Issue by cloudshiftchris** [awslabs/aws-sdk-kotlin#1000]
### Describe the bug

Converting Java SDK code to Kotlin SDK; using StsAssumeRoleCredentialsProvider to provide scoped-down policies for SaaS application, where there is a StsAssumeRoleCredentialsProvider per-tenant that has a dynamic policy limiting access to just that tenants resources (for example, limiting S3 access to /<tenant-id/*).

Kotlin SDK StsAssumeRoleCredentialsProvider does not allow for `policy` attribute for `assumeRole` call, nor does it allow for `sourceId` attribute (which is useful to separate application-assume-role calls from other assume-role calls that you may not want to permit, such as a compromised system making calls from the CLI).

### Expected behavior

StsAssumeRoleCredentialsProvider supports all the capabilities of `assumeRole` call.

### Current behavior

As described earlier, StsAssumeRoleCredentialsProvider is missing `policy` and `sourceId` attributes for `assumeRole` call.

### Steps to Reproduce

n/a

### Possible Solution

Workaround: Given the small size of StsAssumeRoleCredentialsProvider create a custom one that offer the full capabilities.

Fix: much like the Java SDK provide a callback for full customization of the assume-role request

### Context

Unable to directly migrate from Java SDK to Kotlin SDK without building glue code (unfortunate for two missing API attributes).

### AWS Kotlin SDK version used

0.29.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOs

**Comment by lauzadis** [comment]
Thanks for the suggestion! We'll add a task in our backlog to consider exposing these optional parameters in our `StsAssumeRoleCredentialsProvider` to better align with other SDKs like Java.

**Comment by ianbotsf** [comment]
New overloads for the `StsAssumeRoleCredentialsProvider` and `StsWebIdentityCredentialsProvider` constructors have been merged into **main**. The new constructors will allow setting additional parameters to the underlying STS calls such as `policy` and `sourceIdentity`:

```kotlin
val credentialsProvider = StsAssumeRoleCredentialsProvider(
    underlyingCredentialsProvider,
    AssumRoleParameters(
        roleArn = "arn:...",
        policy = "{ ... }",
        sourceIdentity = "sourceId",
    ),
)
```

This feature should be available in the next release of the SDK, tentatively scheduled for 9/7.
