### ISSUE TITLE
CredentialsProviderChain does not accept a list of CredentialsProviders, only varargs

### ISSUE THREAD

**Issue by cloudshiftchris** [awslabs/aws-sdk-kotlin#1001]
### Describe the feature

Currently CredentialsProviderChain is constructed as:

```
public class CredentialsProviderChain(vararg providers: CredentialsProvider)
```

...which is fine for ad-hoc creation of chains.

For configuration-driven use-cases, where a List of providers is created, it would be convenient to accept a List<CredentialsProvider> as well.

### Is your Feature Request related to a problem?

n/a

### Proposed Solution

Provide a secondary constructor to create a CredentialsProviderChain from a List<CredentialsProvider>

### Describe alternative solutions or features you've considered

Currently doing `CredentialsProviderChain(*providers.toTypedArray())`

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.29.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOS

**Comment by lauzadis** [comment]
Thanks for the suggestion! It seems reasonable and we'll add it to our task list.
