### ISSUE TITLE
Broken link to docs/stability.md

### ISSUE THREAD

**Issue by zachary-etelie** [awslabs/aws-sdk-kotlin#1008]
### Describe the issue

The [Getting Started](https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/GettingStarted.md) guide includes a broken link to a [stability guide](https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/stability.md). It's not obvious where this documentation has moved.

### Links

https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/GettingStarted.md
https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/stability.md

**Comment by aajtodd** [comment]
The stability guide/information was merged into our versioning docs [here](https://github.com/awslabs/aws-sdk-kotlin/blob/main/VERSIONING.md#stability-of-the-aws-sdk-for-kotlin). I've put up a PR for fixing the link.

Thanks for pointing this out.
