### ISSUE TITLE
SslSocketFactory on httpClient

### ISSUE THREAD

**Issue by jimarek** [awslabs/aws-sdk-kotlin#1040]
### Describe the issue

Hi I am trying to somehow set sslcontext with my own JavaKeyStore to s3 client. Sofar I haven't found a direct way apart from creating my own implementation of ``HttpClientEngine``

### Steps to Reproduce

``` 
 S3Client {
   httpClient {
     //missing config options?
   }
```

### Current behavior

--

### AWS Kotlin SDK version used

0.32.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macOS Ventura 13.5

**Comment by ianbotsf** [comment]
Thanks for submitting an issue @jimarek. You are correct, there is currently no way to configure a Java KeyStore directly in the bundled HTTP engines. We have backlog item https://github.com/awslabs/smithy-kotlin/issues/820 to add more TLS configuration options. It doesn't explicitly mention Java KeyStores but that's included in the scope.

Writing your own `HttpClientEngine` wrapper is a way forward for now. Additionally, the default OkHttp client engine should also use the KeyStore configured for the JVM so perhaps setting the JVM system properties `javax.net.ssl.keyStore` and `javax.net.ssl.keyStorePassword` may work for your use case.

Generally setting a KeyStore is not necessary for a client to communicate with AWS services. May I ask what you're trying to do?

**Comment by jimarek** [comment]
We are limiting cert root authorities as per company policy.

**Comment by ianbotsf** [comment]
Resolving this issue as we have a backlog item (https://github.com/smithy-lang/smithy-kotlin/issues/820) to implement the requested functionality.
