### ISSUE TITLE
Regression: EcsCredentialsProvider constructor is internal only (#946 / 0.32.2-beta)

### ISSUE THREAD

**Issue by cloudshiftchris** [awslabs/aws-sdk-kotlin#1048]
### Describe the bug

Using `EcsCredentialsProvider` as part of configuring SDK clients, something like: 
```
    return listOfNotNull(
        sessionCredentials?.let {
            StaticCredentialsProvider(Credentials(it.accessKey, it.secretKey, it.sessionToken))
        },
        basicCredentials?.let {
            StaticCredentialsProvider(Credentials(it.accessKey, it.secretKey))
        },
        environmentVariables.takeIf { it }?.let { EnvironmentCredentialsProvider() },
        profile?.let { ProfileCredentialsProvider(profileName = it) },
        container.takeIf { it }?.let { EcsCredentialsProvider() },
        imds.takeIf { it }?.let { ImdsCredentialsProvider() }
    )
```
This worked up to (and including) 0.32.1-beta.  As of 0.32.2 `EcsCredentialsProvider()` fails to compile, indicating that the constructor is internal.  #946 removed `public constructor() : this(PlatformProvider.System)` but did not adjust the primary constructors visibility.

### Expected behavior

`EcsCredentialsProvider` has an accessible constructor and can be external instantiated. 

### Current behavior

Unable to compile against 0.32.2-beta / use `EcsCredentialsProvider`

### Steps to Reproduce

Using 0.32.2-beta create a new `EcsCredentialsProvider()` and observe the compilation failure.

### Possible Solution

Make `EcsCredentialsProvider` constructor public for symmetry with other credentials providers.  Consumers should be able to recreate (selectively / with adjustments) what `DefaultChainCredentialsProvider` does. 

### AWS Kotlin SDK version used

0.32.2-breta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOS

**Comment by ianbotsf** [comment]
Thanks for the bug report @cloudshiftchris. I've reproduced this locally and will have a fix PRed shortly.

**Comment by ianbotsf** [comment]
The fix for this has been merged to **main** and will be included in the next release.
