### ISSUE TITLE
Add information about the Kotlin SDK's support of standardized configuration options to the SDKs & Tools Ref. Guide

### ISSUE THREAD

**Issue by tkhill-AWS** [awslabs/aws-sdk-kotlin#1060]
### Describe the issue

In the [AWS SDKs and Tools Reference Guide](https://docs.aws.amazon.com/sdkref/latest/guide/overview.html), each subsection under [Standardized credential providers](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html) and [Standardized features](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-features.html) contain a table that lists each SDK’s support of settings (config/env properties) for the standardized element.

[Fill in this quip document ](https://quip-amazon.com/dzf8AfD7vPGz/SDK-Reference-Compatibility-Table-expansion) with your responses. Use the links on the left to navigate to the standard feature page and decide if each setting is supported by the SDK. 

- If all settings are supported, put "Yes" in the cell.
- If some are not, put a "Yes" in the cell and list the settings that are not supported in the "Kotlin Notes" column. (See the table at the bottom of this [page](https://docs.aws.amazon.com/sdkref/latest/guide/feature-static-credentials.html) for examples.)
- If none are supported, enter "No". 

### Links

https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html
https://docs.aws.amazon.com/sdkref/latest/guide/standardized-features.html

**Comment by lauzadis** [comment]
Filled in the responses for Kotlin SDK.
