### ISSUE TITLE
forcedPathStyle was needed and removed

### ISSUE THREAD

**Issue by NikolayMetchev** [awslabs/aws-sdk-kotlin#1098]
### Describe the bug

Hi, in the latest version of the AWS SDK forcePathStyle has been removed (https://github.com/awslabs/aws-sdk-kotlin/commit/f6502eb10273ea70bc33712d0d350c1c472266ff) which is a workaround mentioned https://github.com/awslabs/aws-sdk-kotlin/issues/842#issuecomment-1426140171
This has broken the S3 client as described in that bug

### Expected behavior

The s3 workaround to keep working.

### Current behavior

can't use S3 client for CI use case.

### Steps to Reproduce

see original bug for details

### Possible Solution

put back forcedPathStyle

### AWS Kotlin SDK version used

0.33.0-beta 

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

**Comment by NikolayMetchev** [comment]
It is also still in the docs: https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/config-endpoint.html

**Comment by aajtodd** [comment]
Thanks for the bug, indeed this appears to be accidentally removed (the intended removal should have been scoped to just shared configuration properties in `~/.aws/config`). 

Will work on a fix for this.

**Comment by aajtodd** [comment]
This should be fixed in [0.33.1-beta](https://github.com/awslabs/aws-sdk-kotlin/blob/main/CHANGELOG.md#0331-beta---11012023) that was released yesterday.
