### ISSUE TITLE
Allow customizing the StsClient in StsAssumeRoleCredentialsProvider and others

### ISSUE THREAD

**Issue by NikolayMetchev** [awslabs/aws-sdk-kotlin#1132]
### Describe the feature

I would like to be able to turn on detailed logging in the StsClient that is used by StsAssumeRoleCredentialsProvider and possibly other similar classes such as StsWebIdentityCredentialsProvider.

### Is your Feature Request related to a problem?

Debugging credentials issue is not as easy as it could be.

### Proposed Solution

I need to be able to pass in the LogMode to be used when constructing the StsClient. Not sure if it makes sense to pass in an StsClientBuilder or something else to make it more generic. My immediate use case is just for logging. 
Perhaps when you set a credentialProvider in another Client such as the S3Client it could automatically propagate the logging settings.

The change required is here: https://github.com/awslabs/aws-sdk-kotlin/blob/ae1f19d0bc11e3fdb5a4a53d6de6ab1db30c6fbf/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/StsAssumeRoleCredentialsProvider.kt#L104

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.35.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac and Linux

**Comment by lauzadis** [comment]
Thanks for the request, I agree it would make sense to pass the user-configured `LogMode` through to the internal-only clients. I don't think we would make the internal clients configurable since the implementation of the providers are subject to change. 

I posted a draft PR which makes this change: https://github.com/awslabs/aws-sdk-kotlin/pull/1134

**Comment by lauzadis** [comment]
This feature is now available in v1.0.8
