### ISSUE TITLE
Request for Improved Documentation for finding implementation strings

### ISSUE THREAD

**Issue by wickenico** [awslabs/aws-sdk-kotlin#1144]
### Describe the issue

The documentation and code examples in the AWS SDK for Kotlin repository are currently challenging to navigate, making it difficult for developers to find the necessary information and implementation strings quickly.
Also the search on [mvnrepostiroy](https://mvnrepository.com/) really do not lead to the wished implementation.

e.g. **implementation("aws.sdk.kotlin:aws-core-jvm:1.0.10")**

An overview page for all the different implementations would be very helpful at this point to find the right implementation which I want to use for e.g. Lambda, SQS and so on.

### Links

https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/get-started.html

**Comment by ianbotsf** [comment]
Hi @wickenico, I understand you're looking for a better way to discover Maven artifact names for the AWS SDK for Kotlin.

You can find a comprehensive list in our [API reference docs](https://sdk.amazonaws.com/kotlin/api/latest/index.html). Each of the modules listed on that page (e.g., `athena`, `bedrock`, `cloudwatch`, etc.) are the names of Maven artifacts which can be combined with our Maven group (`aws.sdk.kotlin`) and the latest version number to form a Gradle dependency:

```kotlin
implementation("aws.sdk.kotlin:cloudwatch:1.0.13")
```

Additionally, we publish a [Gradle version catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) for our libraries, which allows IDE autocompletion of dependency groups and artifact names, as well as unifying versions across a bundle of dependencies (e.g., keeping the `athena`, `bedrock`, and `cloudwatch` versions all in sync).

To use our version catalog, add the following to your **settings.gradle.kts**:

```kotlin
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }

    versionCatalogs {
        create("awssdk") {
            from("aws.sdk.kotlin:version-catalog:1.0.13")
        }
    }
}
```

Then, to select dependencies, add the following to your **build.gradle.kts**:

```kotlin
dependencies {
    implementation(awssdk.services.athena)
    implementation(awssdk.services.bedrock)
    implementation(awssdk.services.cloudwatch)
}
```

In the above example, note that `awssdk`, `services`, `athena`, `bedrock`, etc. are all symbols, not strings, and should be available in autocompletion in your IDE.

Does that answer your question?

**Comment by wickenico** [comment]
Yes thanks the sdk api page is very useful! :)
