### ISSUE TITLE
Release 1.0.14 does not include smithy 1.0.3

### ISSUE THREAD

**Issue by cloudshiftchris** [awslabs/aws-sdk-kotlin#1150]
### Describe the bug

Release 1.0.14 should have included smithy 1.0.3 ([this issue](https://github.com/awslabs/smithy-kotlin/issues/1008), [this PR](https://github.com/awslabs/aws-sdk-kotlin/commit/da816204c1df0a34fe8da99dde4cce49c760fa83)).

Smithy 1.0.2 is included instead (excerpt from Gradle module metadata): 
```
"dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.0.2"
          }
        },
```

Using the SDK in IntelliJ also shows 1.0.2, as does a Gradle build scan.

### Expected behavior

Smithy 1.0.3 is distributed with AWS Kotlin SDK.

### Current behavior

Smithy 1.0.2 is distributed with AWS Kotlin SDK.

### Steps to Reproduce

Use AWS Kotlin SDK 1.0.14 and observe the transitive dependencies.

### Possible Solution

Release 1.0.15 with a correction for whatever went wrong to include smithy 1.0.3.

### Context

Unable to make select SDK requests with AWS Kotlin SDK 1.0.0+ per [this issue](https://github.com/awslabs/smithy-kotlin/issues/1008), addressed in Smithy 1.0.3.

### AWS Kotlin SDK version used

1.0.14

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macOS Sonoma

**Comment by cloudshiftchris** [comment]
Of note, the changelog text in the PR is also not showing in the release notes for 1.0.14 - its like those (merged) PR changes were skipped.

**Comment by ianbotsf** [comment]
Yes it appears I failed to merge the version bump into the correct branch of **aws-sdk-kotlin**. It has now been merged into the **release** branch and is currently being built and released to Maven.

**Comment by cloudshiftchris** [comment]
Excellent!  thx.

**Comment by ianbotsf** [comment]
Good to hear, thanks for your patience.
