### ISSUE TITLE
Is there a "withJson" operation in the Dynamodb SDK?

### ISSUE THREAD

**Issue by PedroAlvarado** [awslabs/aws-sdk-kotlin#1155]
### Describe the issue

Consider the following code from the Dynamodb Java SDK found in the following [link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaDocumentAPIItemCRUD.html).

Item item = new Item()
    .withPrimaryKey("Id", 210)
    .withString("Title", "Book 210 Title")
    .withString("ISBN", "210-2102102102")
    .withNumber("Price", 30)
    .withJSON("VendorInfo", vendorDocument);

Notice the withJSON. Is the such an equivalent functionality in the DynamoDb Kotlin SDK?

### Steps to Reproduce

N/A

### Current behavior

N/A

### AWS Kotlin SDK version used

1.0.8

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOS

**Comment by aajtodd** [comment]
No there is not currently anything like this in the AWS SDK for Kotlin today. 

I don't see much special about this at first glance as it's still going through `String`. At the moment I'd suggest doing the same and using whatever library you want to serialize and deserialize JSON to and from string.

We'll keep this in mind though as we look at the design for things like the #1148 and #472.
