### ISSUE TITLE
Upgrade to 1.0.38 fails

### ISSUE THREAD

**Issue by steamstreetjon** [awslabs/aws-sdk-kotlin#1184]
### Describe the bug

When upgrading to 1.0.38, the following exception occurs:

aws.smithy.kotlin.runtime.auth.awssigning.UnsupportedSigningAlgorithmException: SIGV4_ASYMMETRIC support is not yet implemented for the default signer.

1.0.37 works fine. 

### Expected behavior

The exception should not be thrown.

### Current behavior

Calls with the EventBridge client are failing. Others may be as well.

### Steps to Reproduce

Update AWS KT dependency to 1.0.38 or greater. Make an API call.

### AWS Kotlin SDK version used

1.0.38

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Lambda Java 17

**Comment by lauzadis** [comment]
Thanks for the report, I replicated the failure and working on a fix.

**Comment by lauzadis** [comment]
Hi, this is fixed in the latest version of the SDK, v1.0.42. Thanks again for the report.
