### ISSUE TITLE
Can't sequentially bootstrap more than one SDK client

### ISSUE THREAD

**Issue by lauzadis** [awslabs/aws-sdk-kotlin#1189]
### Describe the bug

When trying to bootstrap a second SDK client after one has already been bootstrapped, the task succeeds but there is no client generated.

### Expected behavior

The second client should be bootstrapped. 

### Current behavior

The bootstrap task succeeds but does not actually generate a client.

### Steps to Reproduce

```sh
./gradlew --no-daemon -Paws.kotlin.native=false -Paws.services=lambda :codegen:sdk:bootstrap
# observe lambda client is generated
./gradlew --no-daemon -Paws.kotlin.native=false -Paws.services=ec2 :codegen:sdk:bootstrap
# observe task succeeds, but there is no EC2 client
```

### Possible Solution

The bug is related to Gradle caching the `generateSmithyBuild` task results. I noticed this in the logs: `Task :codegen:sdk:generateSmithyBuild UP-TO-DATE`.

Adding a `--rerun-tasks` flag to the bootstrap command fixes the issue, but this problem should be fixed in the Gradle task itself.

### AWS Kotlin SDK version used

1.0.40-SNAPSHOT

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOS

**Comment by aajtodd** [comment]
Yeah I noticed this recently as well I think, this may be fixed in a WIP [branch](https://github.com/awslabs/aws-sdk-kotlin/compare/publishing-qa...publishing-qa-scaffold#diff-85c60e3c4e4de11fd957913876d5cef4f6ee24fc3fa8b3187c2c35cd79ade77fR151).
