### ISSUE TITLE
ClusterDaxClient

### ISSUE THREAD

**Issue by kstag07** [awslabs/aws-sdk-kotlin#1197]
### Describe the feature

Would like a ClusterDaxClient similar to java sdk that can perform read and write operations, current dax client can just manage the cluster but cant interact with dynamo tables

### Is your Feature Request related to a problem?

yes cannot use dax in our application

### Proposed Solution

expand current DaxClient to support these operations

### Describe alternative solutions or features you've considered

create another client for these operations

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.0.44

### Platform (JVM/JS/Native)

JVM

### Operating System and version

iOS, Android, macOS, Windows, Linux

**Comment by ianbotsf** [comment]
Hi @kstag07, you're right there is currently no support for routing DynamoDB access through a DAX cluster in the AWS SDK for Kotlin. [Language-specific DAX clients](http://dax-sdk.s3-website-us-west-2.amazonaws.com/) are separate from the SDKs themselves and thus managed by a different team within AWS.

Please file a support case with AWS via the console. The support team will work with the service team to get your request prioritized.

Are there any other questions I can answer on this topic?

**Comment by kstag07** [comment]
No thats all thankyou
