### ISSUE TITLE
Sending a PutObject request with checksum fails if LogMode is set to LogRequestWithBody

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-kotlin#1198]
### Describe the bug

Request succeeds with LogMode is set to LogRequest but fails when it is set to LogRequestWithBody.

### Expected behavior

Request should succeed as it does when LogMode is set to LogRequest.

### Current behavior

Error is thrown: `Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

### Steps to Reproduce

The following code fails:

```
fun main(): Unit = runBlocking {
    val client = S3Client.fromEnvironment {
        region = "us-west-2"
        logMode = LogMode.LogRequestWithBody
    }

    println(client.putObject {
        bucket = "dayaffe-testing"
        key = "my-metadata-key.txt"
        checksumAlgorithm = ChecksumAlgorithm.Crc32
        body = ByteStream.fromFile(File("non_sparse_file_small.dat"))
    })
}
```

Whereas the follow code succeeds:

```
fun main(): Unit = runBlocking {
    val client = S3Client.fromEnvironment {
        region = "us-west-2"
        logMode = LogMode.LogRequest
    }

    println(client.putObject {
        bucket = "dayaffe-testing"
        key = "my-metadata-key.txt"
        checksumAlgorithm = ChecksumAlgorithm.Crc32
        body = ByteStream.fromFile(File("non_sparse_file_small.dat"))
    })
}
```

### AWS Kotlin SDK version used

Latest

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac 14.2.1

**Comment by aajtodd** [comment]
I've been able to reproduce this. Interestingly it happens whether we request a flexible checksum or not. As long as we trigger chunked signing I'm seeing this.

Will work on a fix, thanks.

**Comment by lauzadis** [comment]
I think it might be caused by [this code segment in `dumpRequest`](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/request/HttpRequestBuilder.kt#L125-L131) which changes the type of the body to ByteArray (no longer an `AwsChunkedSource`/`AwsChunkedByteReadChannel`)
