### ISSUE TITLE
s3TransferManager is uploading files with Content-Encoding metadata empty

### ISSUE THREAD

**Issue by swilsonmelo** [awslabs/aws-sdk-kotlin#1226]
### Describe the bug

s3TransferManager is uploading files with `Content-Encoding` metadata empty, we are uploading some files to s3 with the crt Async client, and the metadata of the objects in s3 contains the `Content-Encoding` key with an empty value

![image](https://github.com/awslabs/aws-sdk-kotlin/assets/34746520/6d5662ca-5f4d-4c7c-a13e-83a191959bf2)

We are uploading text files and we do not need this `Content-Enconding`

We tried setting it to null from the code, but it was still created with an empty value.

### Expected behavior

Objects in s3 without the key `Content-Encoding` in metadata

### Current behavior

Objects in s3 with the key `Content-Encoding` in metadata
![image](https://github.com/awslabs/aws-sdk-kotlin/assets/34746520/6d5662ca-5f4d-4c7c-a13e-83a191959bf2)

### Steps to Reproduce

Dependencies used in the project:
``` 
    implementation(platform("software.amazon.awssdk:bom:2.20.42"))
    implementation("software.amazon.awssdk:s3:2.20.42")
    implementation("software.amazon.awssdk:s3-transfer-manager:2.20.42")
    implementation("software.amazon.awssdk.crt:aws-crt:0.29.10"
``` 

Code where the s3Client and the s3TransferManager are being instantiated

``` kotlin
    @Bean
    fun S3AsyncClient(s3Properties: S3Properties): S3AsyncClient =
        S3AsyncClient.crtBuilder()
            .region(Region.of(s3Properties.region))
            .targetThroughputInGbps(s3Properties.targetThroughputInGbps)
            .minimumPartSizeInBytes(s3Properties.minimumPartSizeInMegaBytes * MB)
            .build()

    @Bean
    fun S3TransferManager(s3AsyncClient: S3AsyncClient): S3TransferManager =
        S3TransferManager.builder()
            .s3Client(s3AsyncClient)
            .build()

``` 

Code that we are using to upload a directory to s3

``` kotlin
override fun uploadDirectoryAsync(destinationFolder: String, directory: Path): CompletableFuture<URI> {
        val directoryUpload = s3TransferManager.uploadDirectory(
            UploadDirectoryRequest.builder()
                .source(directory)
                .bucket(s3Properties.recordingsBucketName)
                .s3Prefix(destinationFolder)
                .build()

        )
        val directoryUriParameters = mapOf("bucket" to s3Properties.recordingsBucketName, "path" to destinationFolder)
        return directoryUpload.completionFuture().thenApply { uriTemplate.expand(directoryUriParameters) }
    }
   
```

### AWS Kotlin SDK version used

implementation(platform("software.amazon.awssdk:bom:2.20.42"))     implementation("software.amazon.awssdk:s3:2.20.42")     implementation("software.amazon.awssdk:s3-transfer-manager:2.20.42")     implementation("software.amazon.awssdk.crt:aws-crt:0.29.10")

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Amazon linux 2 and running locally in MAC OS Sonoma 14.2.1

**Comment by aajtodd** [comment]
Thanks for the issue but you appear to be using the [aws-sdk-java-v2](https://github.com/aws/aws-sdk-java-v2/) and not the AWS SDK for Kotlin.

Unfortunately I can't transfer this automatically to that repo for you because it is in a different GitHub organization. Please open an issue there.
