### ISSUE TITLE
Support for EKS Pod Identities

### ISSUE THREAD

**Issue by felixb** [awslabs/aws-sdk-kotlin#1292]
### Describe the feature

I'd like to use EKS Pod Identities for my kotlin services. Therefore the ContainerCredentialsProvider needs to be implemented.

### Is your Feature Request related to a problem?

There is no kotlin SDK in https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.1.22

### Platform (JVM/JS/Native)

JVM

### Operating System and version

AL2023 for EKS nodes, azul/zulu-openjdk-alpine:21-jre-headless-latest for container

**Comment by lauzadis** [comment]
[EKS Pod identities work by](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html) setting two environment variables, `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` and `AWS_CONTAINER_CREDENTIALS_FULL_URI`, which are then picked up by an SDK's default credentials provider. The Kotlin SDK supports these environment variables through the EcsCredentialsProvider which is a part of the default chain.

Thanks for noting this isn't reflected in the public documentation! We'll get that fixed, but you can definitely use it now.
