### ISSUE TITLE
Add ecs task 'overrides' to eventbridge builder

### ISSUE THREAD

**Issue by samburtonlaurie** [awslabs/aws-sdk-kotlin#1294]
### Describe the feature

I may be missing something but i can't seem to find overrides for an EcsParameters. In the console you can add container overrides like in the SS attached.
<img width="866" alt="image" src="https://github.com/awslabs/aws-sdk-kotlin/assets/139865915/0139bc2b-acd6-4305-a340-29e9751bd69c">

### Is your Feature Request related to a problem?

N/a

### Proposed Solution

Start by adding `public var overrides kotlin.String? = null` into aws.sdk.kotlin.services.eventbridge.model.EcsParameters.Builder

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.1.25

### Platform (JVM/JS/Native)

JVM

### Operating System and version

n/a

**Comment by ianbotsf** [comment]
I'm not familiar with this feature but it appears to be available through [Amazon EventBridge Pipes](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html) and requires using the `PipesClient` via the package **aws.sdk.kotlin:pipes**.

```kotlin
PipesClient.fromEnvironment().use { pipes ->
    pipes.createPipe {
        targetParameters {
            ecsTaskParameters {
                overrides {
                    containerOverrides = listOf(
                        EcsContainerOverride {
                            …
                        }
                    )
                }
            }
        }
    }
}
```

Is that what you're looking for or is yours a different use case?

**Comment by samburtonlaurie** [comment]
I found you can use the [SchedulerClient](https://sdk.amazonaws.com/kotlin/api/latest/scheduler/index.html)  and just put the containeroverrides in the [input of Target](https://sdk.amazonaws.com/kotlin/api/latest/scheduler/aws.sdk.kotlin.services.scheduler.model/-target/input.html).
Thanks for getting back to me @ianbotsf
