### ISSUE TITLE
Telemetry provider implementation for micrometer

### ISSUE THREAD

**Issue by monosoul** [awslabs/aws-sdk-kotlin#1301]
### Describe the feature

`TelemetryProvider` implementation to publish metrics using [micrometer](https://micrometer.io/)

### Is your Feature Request related to a problem?

It would be great if alongside the [OTel implementation](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/observability/telemetry-provider-otel), there was also a micrometer implementation. Unfortunately, there's no adapter from OTel API to micrometer, there's no way to use OTel telemetry provider with micrometer.

### Proposed Solution

Provide `TelemetryProvider` implementation usable with `micrometer`

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

1.2.3

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux 6.8.7

**Comment by ianbotsf** [comment]
Resolved in favor of https://github.com/smithy-lang/smithy-kotlin/issues/1087
