### ISSUE TITLE
AWS SDK's for other languages (python/java) use a no proxy flag when requesting IMDS metadata

### ISSUE THREAD

**Issue by alexeiser** [awslabs/aws-sdk-kotlin#1315]
### Describe the bug

When using Kotlin with a proxy environment or java flags - the ability to fetch information from 169.254.170.2 or 169.254.169.254 will fail. 

other library reference codes:
https://github.com/boto/botocore/blob/1be45c52cf3b743186f9191e7f53d66eefae23cd/botocore/utils.py#L3173
https://github.com/boto/botocore/blob/1be45c52cf3b743186f9191e7f53d66eefae23cd/botocore/utils.py#L3039
https://github.com/aws/aws-sdk-java-v2/blob/master/core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/ConnectionUtils.java#L38

vs

https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt

A simple example:
```
package example.aws.getstarted

import aws.sdk.kotlin.services.sts.StsClient
import aws.sdk.kotlin.services.sts.model.GetCallerIdentityRequest

import kotlinx.coroutines.runBlocking

val REGION = "us-west-2"

fun main(): Unit = runBlocking {
    StsClient { region = REGION}.use { stsClient ->
        val response = stsClient.getCallerIdentity(GetCallerIdentityRequest {})
        println("The user id is ${response.userId}")
        println("The ARN value is ${response.arn}")
    }
}
```
When running on an AWS instance via
`HTTP_PROXY=http://remote-proxy-address:3128 gradle run` 
will throw an exception: 
```
Exception in thread "main" aws.smithy.kotlin.runtime.identity.IdentityProviderException: No identity could be resolved from the chain: CredentialsProviderChain -> SystemPropertyCredentialsProvider -> EnvironmentCredentialsProvider -> ProfileCredentialsProvider -> StsWebIdentityProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider
```
With out the HTTP_PROXY, or with `NO_PROXY=169.254.169.254` it will succeed.

Python and the java SDK do not fail.

### Expected behavior

Requests to the instance metadata URLs should not respect the proxy flag (like other AWS SDKs)

### Current behavior

Traffic is routed to the defined proxy - which can't (and SHOULD NOT) fetch the instance metadata as the connection is originating from a different host.

### Steps to Reproduce

requires 2 aws instances
1 - deploy a HTTP proxy (e.g. squid, or caddy)
2 - configure a test application that tries to use the instance metadata to fetch an AWS Instance Profile role.
3 - attempt to fetch the instance role with a proxy, and with out.

### AWS SDK for Kotlin version

aws.sdk.kotlin:sts:1.2.15 (and tried with 1.0.30)

### Platform (JVM/JS/Native)

kotlin jvm 1.9.22 on 

### Operating system and version

ubuntu 22.04

**Comment by lauzadis** [comment]
Thanks for the report! I've verified that proxied requests to IMDS fail as you show, and opened a PR to fix it.

**Comment by lauzadis** [comment]
The PR has been merged and changes will be present in the next release **v1.2.24**, scheduled for tomorrow.

**Comment by alexeiser** [comment]
Awesome - thanks for getting it fixed.
