### ISSUE TITLE
DynamoDbClient.scanPaginated ignores exclusiveStartKey

### ISSUE THREAD

**Issue by thake** [awslabs/aws-sdk-kotlin#1330]
### Describe the bug

The method DynamoDbClient.scanPaginated ignores the initial exclusiveStartKey.

### Expected behavior

The inital passed exclusiveStartKey is honored.

### Current behavior

The inital passed exclusiveStartKey is ignored.

### Steps to Reproduce

```kotlin 
val table = "table-to-scan"
val lastKey = mapOf("primaryKey" to AttributeValue.S("lastKeyPk"))
val result = client.scanPaginated {
    tableName = table
    exclusiveStartKey = lastKey
}
val simpleScanResult = client.scan {
    tableName = table
    exclusiveStartKey = lastKey
}
//results should have the same item at pos 0, but they don't as exclusiveStartKey is ignored.
```

### AWS SDK for Kotlin version

2

### Platform (JVM/JS/Native)

JVM

### Operating system and version

Mac OS 14

**Comment by 0marperez** [comment]
Hello @thake, the fix for this issue was released. I'll mark this issue as resolved but if you're still having issues feel free to @ me.

**Comment by 0marperez** [comment]
Fixed by https://github.com/smithy-lang/smithy-kotlin/pull/1101
