### ISSUE TITLE
Support for Product Advertising API

### ISSUE THREAD

**Issue by aschulz90** [awslabs/aws-sdk-kotlin#1405]
### Describe the feature

Please add a service for the [Product Advertising API](https://webservices.amazon.com/paapi5/documentation/) to query products off of Amazon.

### Is your feature request related to a problem?

The [PAAPI documentation](https://webservices.amazon.com/paapi5/documentation/with-sdk.html) provides a Java SDK, but the latest version is only distributed as a zip and the last published version is from 2017 ([Maven](https://central.sonatype.com/artifact/com.amazon.paapi/paapi-java-sdk/overview)).
It would be great if the `ProductAdvertisingAPI` AWS service could directly be queried through this Kotlin SDK instead.

### Describe alternative solutions or features you've considered

Since the service is just signed HTTP requests, one can maintain the request and response models by themself; and then sign the request as described [here](https://github.com/awslabs/aws-sdk-kotlin/issues/999#issuecomment-1997702298). 

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS SDK for Kotlin version

v1.3.32

### Platform (JVM/JS/Native)

JVM

### Operating system and version

All

**Comment by lauzadis** [comment]
Hello, thanks for submitting this request.

 The PAAPI SDKs are maintained by the PAAPI team and the AWS SDK for Kotlin is unable to implement support for it in the way we do for AWS services. I've opened an internal feature request to their team (PAAPI-FR-172).

In the meantime, the PAAPI team [does offer documentation on making requests without an SDK](https://webservices.amazon.com/paapi5/documentation/without-sdk.html), and you've correctly identified how to sign SigV4 requests yourself using the AWS SDK for Kotlin's signer. I would recommend pursuing that route. Let me know if you have any questions with this process!
