### ISSUE TITLE
Add BOM to version catalog

### ISSUE THREAD

**Issue by cloudshiftchris** [awslabs/aws-sdk-kotlin#1440]
### Describe the feature

atm the bom is not part of the SDK-published version catalog.  When using the BOM with the version catalog you have to specify the SDK version twice - once for the BOM, and again for the version catalog. 

```
    implementation(platform(libs.awssdk.kotlin.bom))  // from libs.versions.toml
    implementation(awssdk.services.codeartifact) // from SDK version catalog
    implementation(awssdk.services.ecr)
    implementation(awssdk.services.s3)
    implementation(awssdk.services.ssm)
    implementation(awssdk.services.rds)
    implementation(awssdk.services.resourcegroupstaggingapi)
    implementation(awssdk.services.route53)
    implementation(awssdk.services.dynamodb)
    implementation(awssdk.services.secretsmanager)
    implementation(awssdk.runtime.smithy.kotlin.http.client.engine.okhttp)
```

### Is your feature request related to a problem?

While this doesn't appear to pose any material issue having the SDK version in two places is at best confusing.  The BOM will trump whatever the version catalog specifies.

### Proposed Solution

Add the BOM to the version catalog, e.g. `awssdk.bom`

### Describe alternative solutions or features you've considered

The sample above shows the workaround of specifying the BOM separately

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS SDK for Kotlin version

1.3.51

### Platform (JVM/JS/Native)

JVM

### Operating system and version

MacOS

**Comment by lauzadis** [comment]
Hi @cloudshiftchris, the BOM should be available in the version catalog after today's release. Thanks again for the great feature requests

**Comment by cloudshiftchris** [comment]
Amazing, thanks @lauzadis.
