### ISSUE TITLE
Kotlin version of the Encryption SDK

### ISSUE THREAD

**Issue by NikolayMetchev** [awslabs/aws-sdk-kotlin#1447]
### Describe the feature

It would be good to have a Kotlin version of Encryption SDK. Right now there is only a Java version (https://github.com/aws/aws-encryption-sdk-java/)

### Is your feature request related to a problem?

We need to use this in AWS Lambda and we want to avoid having both the Kotlin SDK and the Java SDK to bloat our lambdas.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS SDK for Kotlin version

Latest

### Platform (JVM/JS/Native)

JVM

### Operating system and version

All

**Comment by lauzadis** [comment]
Hi Nikolay, thanks for the feature request. These products are not maintained by the AWS SDKs team but I've forwarded your request to the appropriate group.

**Comment by lauzadis** [comment]
We will keep this ticket open to track public support for the feature. React to the issue with a thumbs-up 👍 if you would also benefit from this new library. 

Internal reference: `V1557172983`

**Comment by lauzadis** [comment]
We'll be closing this in favor of the internal issues / issue in [aws-cryptographic-material-providers-library](https://github.com/aws/aws-cryptographic-material-providers-library)
