### ISSUE TITLE
s3 custom treatment of GetBucketLocation response

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#194]
@jdisanti discovered a discrepancy: [S3 documentation specifies a form of XML](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) for the response of `GetBucketLocation`, and then provides an example that does not follow the specification.  @rcoh found that the Go SDK had [this issue](https://github.com/aws/aws-sdk-go-v2/issues/908) and [implemented a customization](https://github.com/aws/aws-sdk-go-v2/pull/1027) to deal with this.

Acceptance criteria:
* responses to the getBucketLocation operation should deserialize as expected into the response properties.

**Comment by aajtodd** [comment]
https://smithy.io/2.0/aws/customizations/s3-customizations.html#aws-customizations-s3unwrappedxmloutput-trait

**Comment by ianbotsf** [comment]
This seems to have been implemented already in #174, albeit not via [`s3UnwrappedXmlOutput`](https://smithy.io/2.0/aws/customizations/s3-customizations.html#aws-customizations-s3unwrappedxmloutput-trait).
