### ISSUE TITLE
Enable awsJson service protocol tests

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#196]
See https://github.com/awslabs/smithy/tree/main/smithy-aws-protocol-tests/model/awsJson1_1/services

Currently this is only machinelearning service

Acceptance criteria:
* service-based protocol tests are generated and pass

Relates to https://github.com/awslabs/smithy-kotlin/issues/278

**Comment by aajtodd** [comment]
Implemented in #378
