### ISSUE TITLE
S3 Customization to handle status code 200 Errors

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#199]
Related to https://github.com/awslabs/smithy-kotlin/issues/323

Relevant information from @aajtodd copied from related ticket:

Here is what Go does for status code 200 Errors:

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/S3ErrorWith200Status.java#L18
https://github.com/aws/aws-sdk-go-v2/blob/d05dd9b08d180c3696c33130548881966b56ea29/service/s3/internal/customizations/handle_200_error.go#L33

Once 200 errors are properly parsed, ensure that standard retry logic properly retries on `InternalError` as noted in the comment below.

**Comment by aajtodd** [comment]
`new_retries` SEP recently added 
`200         | InternalError                          | s3   `

**Comment by aajtodd** [comment]
Apparently DeleteObjects can also return a 200 error response: https://github.com/awslabs/aws-sdk-rust/issues/873

_Likely_ any control plane API is able to return a 200 error response.
