### ISSUE TITLE
Add support for SigV4 chunked signing

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#209]
Currently `HttpBody.Streaming` payloads are only supported through `UNSIGNED-PAYLOAD` (see `AwsSigV4SigningMiddleware`). AWS SDK's should default to signed payloads whenever possible though with few exceptions:

1. Customer explicitly requests unsigned payload 
    * assuming we even give a knob to do so, the context attribute exists already though to support the unsigned payload trait (see  `AuthAttributes.UnsignedPayload`)
2. Customer gives us an unbounded stream (e.g. `ByteStream.Reader -> HttpBody.Streaming`)

In the case of (2) there are only 3 options:
1. use unsigned payload (not desired as the default)
2. the stream must support a seek operation such that it can be read multiple times 
    * computing the signature for a single chunk requires consuming the stream
    * `SdkByteReadChannel` is a "single use/pass" channel and the underlying SDK mechanism that supports async byte streams. It does not (and should not) arbitrarily support seeking because doing so would require buffering ALL of the writes in-memory
3. use [chunked signing](https://docs.amazonaws.cn/en_us/AmazonS3/latest/API/sigv4-streaming.html) such that the stream only needs to be consumed once
    * NOTE: S3 still requires a known a `Content-Length` even for chunked signing so we can't support arbitrary streams of unknown length. It would be nice to be able to provide a `UriContent` type though that could e.g. upload content from a URI (assuming the content gives a `Content-Length`). 

we would hopefully be able to default to chunked signing when given a stream such that rewinding or special casing files isn't necessary for computing the signature.

It's unclear what services or individual operations support chunked signing though. The CRT team indicated the following:
> Generally only streaming operations will support chunked signing, and all other operations defined by the service will use conventional sigv4.
> Transcribe Streaming supports chunked signing, but not the `aws-chunked` content-encoding

**Comment by lauzadis** [comment]
When we are sending chunked requests to S3, we don't need to include the Content-Length header.

> Specify the `Transfer-Encoding` HTTP header. If you include the `Transfer-Encoding` header and specify any value other than identity, you must omit the Content-Length header.

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

We will be specifying a value of `chunked` for `Transfer-Encoding`, so I'm pretty sure we can work around an un-rewindable stream.

**Comment by aajtodd** [comment]
> When we are sending chunked requests to S3, we don't need to include the Content-Length header.

This unfortunately isn't true. S3 requires `Content-Length` even when streaming (see https://github.com/awslabs/aws-sdk-kotlin/issues/612#issuecomment-1136110897)

> so I'm pretty sure we can work around an un-rewindable stream.

Correct, as long as the stream still supplies a total size then we can send it with `Transfer-Encoding: aws-chunked` and calculate the signature as we are sending it for each chunk.

**Comment by lauzadis** [comment]
Resolved via #747
