### ISSUE TITLE
Consider returning service-generated requestId in all response types, not just errors

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#211]
The Ruby v2 SDK does this, and they say this is to help customers debug problems that may not be related to service exceptions.

Acceptance criterea:
* determine if anything in our architeture would prevent this / other compat concerns
* get some customer or SDK team data about if this is something we should add to our SDK
* provide a design

**Comment by ianbotsf** [comment]
This information will be made available through [inceptors](https://github.com/awslabs/smithy-kotlin/issues/122) eventually, not directly in response types.
