### ISSUE TITLE
AWS ARN Parser

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#215]
Implement an ARN parser and supporting classes. 

Consider how this will integrate with the various endpoint customizations (e.g. S3 virtual host, Westeros, MRAP) etc which is the primary use case for this.

**Comment by bwrichik** [comment]
I was using parsing ARNs are part of tracking QuickSIght usage. It would have been great if I could have used the Kotlin parser rather than the Java parser.

**Comment by lauzadis** [comment]
We have no plans to expose a public ARN parser at this time. This issue was created to track implementation of an internal-only ARN parser, which we now have. Closing this issue for now.
