### ISSUE TITLE
Consistent handling of dualstack endpoint configuration

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#237]
There is an ongoing effort to standardize configuration and behavior of dual-stack enabled service endpoints.

Related QUIP: /SVGJAQmKMtaC/UseDualstackEndpoint-Config

**Comment by aajtodd** [comment]
This will mostly be OBE by endpoints 2.0 work but we will still need to support shared config and env variable (and JVM system property) options (if they exist)

**Comment by lucix-aws** [comment]
OBE by https://github.com/awslabs/aws-sdk-kotlin/pull/869
