### ISSUE TITLE
S3: SSECustomerKey and CopySourceSSECustomerKey should be blob shapes

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#248]
*internal id*: 176559035

**Comment by ianbotsf** [comment]
I question whether this is necessary after all. It appears that [Java](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CreateMultipartUploadRequest.html#sseCustomerKey()), [Python](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/create_multipart_upload.html), [JavaScript](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/createmultipartuploadcommandinput.html#ssecustomerkey-2), and .[NET](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TInitiateMultipartUploadRequest.html) all treat this as a string, not a blob.

**Comment by ianbotsf** [comment]
We've decided not to do this.
