### ISSUE TITLE
SSO Credential Provider

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#252]
* /seps/accepted/shared/sso-provider/
* /seps/accepted/shared/sso-login-flow/

*internal id*: 174880365

**Comment by cprice404** [comment]
Is there any ETA for this?

**Comment by aajtodd** [comment]
@cprice404 Not yet. It is definitely on our short term radar but I can't give an exact ETA yet. I saw your comment in the other ticket I'm going to drop those details here as well:

> I am trying to do dev work where I run some SDK code on my laptop and have it make API calls
up to my AWS account. We do not use static credentials nor default profiles, so my auth info
is currently all provided via sso/credential_process config inside of profiles in ~/.aws/config.
