### ISSUE TITLE
Customer can add headers to any operation call

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#255]
Support ability for customers to add headers to requests.  See here for an example of a service that provides functionality via custom (unmodeled) headers: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_PutLogEvents.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by aajtodd** [comment]
closing as dup of https://github.com/awslabs/smithy-kotlin/issues/122
