### ISSUE TITLE
Allow customers to call HttpClientEngine instances directly

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#291]
There is some coroutine handling going on at the layer above, `SdkHttpClient`, that needs to be pushed down, or an alternative approach such that instances of `HttpClientEngine.roundTrip()` can be called from customer code.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by aajtodd** [comment]
Closing this as the intention is for `HttpClientEngine` to be an abstraction meant for the SDK to use/consume and that requires going through `SdkHttpClient`.
