### ISSUE TITLE
Move implementation of SdkClient::serviceName to companion object

### ISSUE THREAD

**Issue by efenderbosch** [awslabs/aws-sdk-kotlin#306]
## Describe the Feature/Problem
We are using the service name to configure endpoints for testing. So we can point S3 tests to Localstack, for example.

In the Java SDK we can get the service name from `S3Client.SERVICE_NAME`. In the current Kotlin SDK we must have a client already built in order to access `S3Client::serviceName`, but we need it while we are in the process of building the client.

For example, this is how we built our S3 client w/ the Java SDK:
```kotlin
val s3Client: S3Client by lazy {
    S3Client.builder()
        .credentialsProvider(credentialsProvider)
        .applyMutation(EndpointOverride(S3Client.SERVICE_NAME))
        .build()
    }
```

And `EndpointOverride` would look at sys props/env vars to determine if the sevice's endpoint should be overridden.

I can build a new `S3Client` like this:
```kotlin
val s3Client: S3Client by lazy {
    S3Client {
        credentialsProvider = credentialsProvider
        endpointResolver = endpointResolver("S3")
    }
}
```
But it would be nicer if `S3` was a constant from the SDK, not a freestyle `String`:

```kotlin
val s3Client: S3Client by lazy {
    S3Client {
        credentialsProvider = credentialsProvider
        endpointResolver = endpointResolver(S3Client.serviceName)
    }
}
```

## Proposed Solution
Implement `SdkClient` on the client's companion object instead of an instance function.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by kiiadi** [comment]
We use the Java SDK's `<client>.SERVICE_NAME` in multiple places in the AWS JetBrains IDE Toolkit ([example](https://github.com/aws/aws-toolkit-jetbrains/blob/13a73f8345e5a9e50934f1ed46b3f7bab9456d92/jetbrains-core/src/software/aws/toolkits/jetbrains/core/explorer/nodes/S3ExplorerRootNode.kt#L11)), we also use the `<client>.SERVICE_METADATA_ID` to look up metadata about the endpoint for a given service - which helps us construct a client generically ([example](https://github.com/aws/aws-toolkit-jetbrains/blob/13a73f8345e5a9e50934f1ed46b3f7bab9456d92/core/src/software/aws/toolkits/core/ToolkitClientManager.kt#L55)). 
  
Most of the time these are actually the same, but there's instances where they can be different, (eg. Ecr where "Service Name" is `ecr`, and the "Metadata ID" is `api.ecr`.

**Comment by aajtodd** [comment]
@efenderbosch Something like this seems doable. 

@kiiadi `api.ecr` doesn't appear to actually be "metadata/sdkId" for ECR. It appears to be the [endpointPrefix](https://github.com/awslabs/aws-sdk-kotlin/blob/88a469e20503e7763439789a31621a8d17c3b72c/codegen/sdk/aws-models/ecr.2015-09-21.json#L145). 

We do generate the unique `sdkId` as a `const` into the top level service package:

e.g.
```kotlin
const val ServiceId: String = "ECR"
```

Which can be accessed as `aws.sdk.kotlin.services.ecr.ServiceId`


Client name is a really poor thing to predicate off of, I think the unique [service id](https://awslabs.github.io/smithy/1.0/spec/aws/aws-core.html#sdkid) would be best.

**Comment by efenderbosch** [comment]
`aws.sdk.kotlin.services.foo.ServiceId` seems sufficient for our needs. Some have spaces in the name, but we can remove those.

**Comment by ianbotsf** [comment]
Resolving this issue as it seems like `ServiceId` will meet your needs. Feel free to re-open if there are further questions.
