### ISSUE TITLE
StaticEndpointResolver with custom port does not connect with that port.

### ISSUE THREAD

**Issue by jurmous** [awslabs/aws-sdk-kotlin#310]
## Describe the bug

When setting up a port with the StaticEndpointResolver it does not connect with port passed to the EndPoint

## Expected Behavior

Connects to the server on expected port

## Current Behavior

Does not connect to server on expected port.

```
Exception in thread "main" software.amazon.awssdk.crt.http.HttpException: socket connection refused.
	at software.amazon.awssdk.crt.http.HttpClientConnection.onConnectionAcquired(HttpClientConnection.java:85)
```

## Steps to Reproduce

Set up a local DynamoDB
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

```
val ddb = DynamoDbClient {
        region = "eu-west-2"

        this.endpointResolver = StaticEndpointResolver(
            Endpoint("localhost", "HTTP", 8000)
        )
    }
```

## Possible Solution

The port is not passed to the Http Engine. (Checked it with a manual implementation of HttpClientEngine)

## Context

I cannot connect to local running DynamoDB
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

## Your Environment

* AWS Kotlin SDK version used: 0.4.0-alpha
* Platform (JVM/JS/Native): JVM
* Operating System and version: macOS 11.5.2

**Comment by ianbotsf** [comment]
Looks like _none_ of the endpoint resolvers' ports are respected. Fix coming soon...
