### ISSUE TITLE
Determine proper modeling of org.jetbrains.kotlinx:kotlinx-coroutines-core dependency in generated Service SDKs

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#363]
## Describe the bug

Currently customers do not need to explicitly depend upon `org.jetbrains.kotlinx:kotlinx-coroutines-core` in their programs that depend upon AWS Service SDKs.  This may not be the best approach as there may be versioning issues of mixing what the customer may have with what the SDKs build against.

acceptance criteria: determine if it is safe to bundle this dependendy.  If not update dependency model such that an explicit dependency is required.

## Possible Solution

Modeling the dependency as `implementation` over `api`.

## Your Environment

* AWS Kotlin SDK version used:
* Platform (JVM/JS/Native):
* Operating System and version:

**Comment by aajtodd** [comment]
Closing since `kotlinx-coroutines-core` is now an `api()` requirement of paginators.
