### ISSUE TITLE
Generate Presigners that sign the querystring rather than headers

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#382]
Presigned URLs are easier to work with than presigned requests, because of the extra complexity of serializing/deserializing lists of lists (headers). vs just a URL as a string.

Currently the SDK generates most presigners to use headers. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by ianbotsf** [comment]
We'll handle this in [smithy-kotlin#755](https://github.com/awslabs/smithy-kotlin/issues/755).
