### ISSUE TITLE
Gradle errors with Dokka in IntelliJ

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#400]
## Describe the bug

The **aws-sdk-kotlin** project fails to load in IntelliJ in some circumstances. When the bug is present, Gradle loads/refreshes fail with the error message:

```
Could not create task ':aws-runtime:dokkaGfm'.
Cannot change dependencies of dependency configuration ':aws-runtime:dokkaGfmPlugin' after it has been resolved.
```

This error isn't reproduced when building from the command line. Disabling all Dokka components in Gradle scripts resolves the issue.

## Expected Behavior

I expect to be able to load/refresh **aws-sdk-kotlin** within IntelliJ.

## Current Behavior

See above description.

## Steps to Reproduce

* Check out a fresh copy of **aws-sdk-kotlin**
* Load the project in IntelliJ
* Observe that the Gradle load fails with the above error message
* Refresh/reload Gradle within the IDE
* Observe that the Gradle load fails with the above error message

## Possible Solution

Unknown, all I have is a workaround of completely disabling all Dokka components in Gradle scripts. This allows Gradle loading to succeed although it's not viable as a long-term solution.

## Context

This issue used to occur only occasionally for me but now happens reliably for every new and existing workspace.

## Your Environment
* AWS Kotlin SDK version used: 0.10.0-SNAPSHOT
* Platform (JVM/JS/Native): JVM 1.8.311
* Operating System and version: Windows 10 20H2
* IDE version: IntelliJ 2021.2.2 Ultimate Edition, Build #IU-212.5284.40, built on September 13, 2021

**Comment by ianbotsf** [comment]
Issue no longer occurs with latest codebase.

**Comment by rmarrowstone** [comment]
For folks who may stumble on this in future... for me this was caused by a mismatch between the Kotlin version I had in IntelliJ (1.6) vs what was set in the `gradle.properties` (1.7). Upgrading my Kotlin version for IntelliJ resolved the issue.
