### ISSUE TITLE
Add DEBUG-level summary of API calls

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

The SDK should emit a log message at DEBUG level summarizing an API call. This should contain minimal, useful information to assist in debugging scenarios by end-users.

Proposed example:

```
DEBUG ApiCallLogger - sdkRequestId: 12345678-9abc-def0-1234-56789abcddef0; service: S3; operation: ListBuckets; - Request size: 4kb. Response size: 8kb. Received response in 100ms. HTTP status code: 200.
```

## Is your Feature Request related to a problem?

None at this time.

## Proposed Solution

See above for proposed example.

## Describe alternatives you've considered

None at this time.

## Additional Context

This will add additional per-call debugging capabilities when users explicitly opt into DEBUG-level logging.

- [x] I may be able to implement this feature request

**Comment by aajtodd** [comment]
closed by https://github.com/awslabs/smithy-kotlin/pull/547
