### ISSUE TITLE
Call the Kotlin SDK from Java

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Support the ability to use the Kotlin SDK (JVM platform) from Java programs.

## Is your Feature Request related to a problem?

Currently the Kotlin SDK does not provide a way of calling service operations in a way that is compatible with Java.  Additionally, the model type builders, while technically usable, are not simple or obvious to use when coming from a Java builder perspective.

## Proposed Solution

Provide a capability in the SDK such that SDK functionality can be used from Java.  This may be built-in or as an additional add-on layer.

## Describe alternatives you've considered

Due to inherent compatibility issues between Kotlin and Java concurrency, there is not a way of enabling Java interop without updating the codegen on service client interfaces and their implementations.

## Additional Context

- [X] I may be able to implement this feature request

**Comment by cloudshiftchris** [comment]
Use the AWS Java SDK, which is idiomatic for Java usage.  The Kotlin SDK is idiomatic for Kotlin, and includes things that don't exist in Java - DSL builders, coroutines (suspend functions) - why expend effort bridging all those when you can just import the Java SDK.

**Comment by RanVaknin** [comment]
Hi @kggilmer ,

This was left open for a few years to gauge interest. Unfortunately there are no additional upvotes. We also suspect that recent changes to the SDK address some of the concerns made here. Therefore we are going to go ahead and close this. 

If you need anything else, please consider opening a new issues.

Thanks,
Ran~
