### ISSUE TITLE
Serverless Aurora RDS support in Kotlin

### ISSUE THREAD

**Issue by sybarite400** [awslabs/aws-sdk-kotlin#455]
Access to the Serverless Aurora Rds via a native Rds client in Kotlin

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Please add support for Rds access (Mysql and postgres) via kotlin sdk.

## Describe alternatives you've considered

Currently this is supported in Java.
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javav2/example_code/rds

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by aajtodd** [comment]
@sybarite400 Thanks for the feature request!

Can you clarify what you are looking for? The AWS SDK for Kotlin does currently support the RDS control plane APIs. You can find some samples [here](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/kotlin/services/rds)
