### ISSUE TITLE
isAndroid() returning true when running JVM code in Kotlin Multiplatform shared code

### ISSUE THREAD

**Issue by joreilly** [awslabs/aws-sdk-kotlin#459]
### Describe the bug

If I try to to run code in `jvmMain` source in a Kotlin Multiplatform module (that targets `jvm` and `android`) I'm getting following error.

```
Unable to open library in jar for AWS CRT: /android/x86_64/libaws-crt-jni.dylib
```

The issue seems to be that following is returning true

```
    private static boolean isAndroid() {
        try {
            Class.forName("android.os.Build");
            return true;
        } catch (ClassNotFoundException ex) {
            return false;
        }
    }
```    

### Expected behavior

It should load osx version of dylib

### Current behavior

It tries to load android version of dylib

### Steps to Reproduce

Run code in `jvmMain` source set in a Kotlin Multiplatform project with `android()` and `jvm()`  targets

### AWS Kotlin SDK version used

0.9.4

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macOS 11.4

**Comment by joreilly** [comment]
ok, I guess not too surprising given following on command line (am running `main` directly from Android Studio here fwiw...will try command line and also not sure if IntelliJ behaves any differently here)

```
-classpath /Users/joreilly/Library/Android/sdk/platforms/android-31/android.jar
```

**Comment by joreilly** [comment]
Confirmed that running in IntelliJ and I don't see this issue.

**Comment by aajtodd** [comment]
@joreilly Thanks for the bug report. It seems like default behavior of Android Studio is causing this if I'm following correctly. 

Would you mind sharing your config that didn't work as well as the configuration that fixed it? Perhaps there is something we can do to make this a better experience or at the very least document a working solution for people.

**Comment by joreilly** [comment]
@aajtodd so issue seemed to be if I used default JRE as shown in first screenshot here (it included `android.jar` in classpath in that case)....it was ok when I switched to `11`

![Uploading Screenshot 2021-
<img width="1191" alt="Screenshot 2021-12-05 at 15 32 05" src="https://user-images.githubusercontent.com/6302/144753028-c7fecd3f-2e00-4603-8106-4b0831f908df.png">
12-05 at 15.31.47.png…]()

**Comment by joreilly** [comment]
btw this is what I was trying to do :) https://twitter.com/joreilly/status/1467514847667658755?s=20

**Comment by aajtodd** [comment]
@joreilly Thanks for sharing! Really cool.

I'm going to go ahead and close this issue since you now have it working. 

Please do share any feedback you have (good or bad).
