### ISSUE TITLE
Provide a high-level DynamoDB client

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-sdk-kotlin#472]
### Describe the feature

Provide a high-level DynamoDB client which performs object-data mapping, similar to [the DynamoDBMapper for the AWS SDK for Java](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html).

### Is your Feature Request related to a problem?

Loading and inserting values using the attribute values apis is tedious

### Proposed Solution

see the existing aws java sdk v1 (or v2) DynamoDbMapper

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

all

### Platform (JVM/JS/Native)

all

### Operating System and version

all

**Comment by ianbotsf** [comment]
Hi @michaelbrewer, thank you for the feature request. We'd definitely love to provide the equivalent of DynamoDbMapper in the future. I'll leave this request open to allow others to 👍 upvote and that may help us with prioritization.

**Comment by ianbotsf** [comment]
Additional context from #76:
> We might be able to do this as a compiler plugin and generate rather optimized code so that we don't have to rely on annotation processing (which I believe is JVM only at the moment) OR on reflection capabilities.

> See a good high level overview of considerations from rust SDK: awslabs/aws-sdk-rust#70

**Comment by popematt** [comment]
Another possibility might be to leverage [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization). I haven't looked into it too thoroughly yet, but it seems like it would be straightforward to convert classes to and from DynamoDB Json.

**Comment by randyhbh** [comment]
Any update on this issue?

**Comment by ianbotsf** [comment]
We have no new updates to share at this time. Providing a high-level DynamoDB client remains on our roadmap but will likely not be prioritized until the underlying SDK itself (including the low-level DynamoDB client) is stable and released as 1.0.

**Comment by scmorse** [comment]
@ianbotsf Any updates on the priority / timeline for implementing an 'Enhanced' dynamodb client? 🙏

**Comment by ianbotsf** [comment]
Yes, we are currently putting the finishing touches on a Dev Preview version of the high-level DynamoDB client, which will be called "DynamoDB Mapper". This version will have a subset of the full features expected in the final version and will not be recommended for use in production. But it should provide users an opportunity to test out the mapper implementation so far and give feedback on what works and what doesn't.

I can't commit to an exact date but we hope to release the Dev Preview in the coming weeks. When that happens, we'll announce it in several channels including this issue. We'll also add some documentation to our Developer Guide to explain the basics and get people started. It's been a long journey to get to this point where we _could_ release a DynamoDB high-level library and we're as eager as you are to get this out for people to use. Thanks for your patience!

**Comment by ianbotsf** [comment]
📣 The [**Developer Preview** of **DynamoDB Mapper** for Kotlin is now available](https://aws.amazon.com/blogs/developer/announcing-dev-preview-of-dynamodb-mapper-for-kotlin/)! Please check it out and let us know what you think.

**Comment by MarcelReiter** [comment]
Hey @ianbotsf,
can you provide a rough estimation on when this feature might become a stable?
I'd really like to use this in production 😍

**Comment by ianbotsf** [comment]
We'd like to finish up the DynamoDB Mapper this year if possible but we have to slot it in with other priorities. I'm afraid I can't give more concrete timelines than that.

**Comment by ianbotsf** [comment]
The **[v1.8.20](https://github.com/aws/aws-sdk-kotlin/releases/tag/v1.8.20)** release of the AWS SDK for Kotlin [includes the full, GA version of DynamoDB Mapper](https://aws.amazon.com/blogs/developer/announcing-general-availability-of-dynamodb-mapper-for-kotlin/). This release adds new support for:

* the `updateItem` operation and update expressions DSL
* batch and transactional operations
* annotation-driven atomic counters and TTL fields
* annotations for custom attribute converters and secondary indexes
* various bug fixes

Checkout the [announcement post](https://aws.amazon.com/blogs/developer/announcing-general-availability-of-dynamodb-mapper-for-kotlin/) and the updated [Developer Guide](https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/ddb-mapper.html) for more details. Happy mapping! :grin:
