### ISSUE TITLE
aws.sdk.kotlin:cognito does not exist

### ISSUE THREAD

**Issue by KristapsKrumins** [awslabs/aws-sdk-kotlin#477]
### Describe the issue

In the documentation "Setting up the AWS SDK for Kotlin" there is a reference to `implementation("aws.sdk.kotlin:cognito:0.9.4-beta")` but this library does not exist in maven. https://mvnrepository.com/artifact/aws.sdk.kotlin/cognito 
<s>How can I use Amazon Cognito with Kotlin SDK?</s> It should be aws.sdk.kotlin:cognitoidentityprovider

### Links

https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/setup.html

**Comment by anyo** [comment]
Documentation is pointing to 
`implementation("aws.sdk.kotlin:cognito:0.9.4-beta")`

instead I had to change it to below to get it working
```
implementation("aws.sdk.kotlin:cognitoidentity:0.9.4-beta")
implementation("aws.sdk.kotlin:cognitoidentityprovider:0.9.4-beta")
```

**Comment by tkhill-AWS** [comment]
When we rewrote the Kotlin Dev Guide (published in Oct. 2022),[ this page](https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/setup.html#setup-create-projet-file) was updated. 
The dependencies are now listed as:
```
dependencies {
    implementation("aws.sdk.kotlin:s3:0.17.5-beta")
    implementation("aws.sdk.kotlin:dynamodb:0.17.5-beta")
    implementation("aws.sdk.kotlin:iam:0.17.5-beta")
    implementation("aws.sdk.kotlin:cloudwatch:0.17.5-beta")
    implementation("aws.sdk.kotlin:cognito:0.17.5-beta")
    implementation("aws.sdk.kotlin:sns:0.17.5-beta")
    implementation("aws.sdk.kotlin:pinpoint:0.17.5-beta")
    testImplementation(kotlin("test"))
}
```

**Comment by aajtodd** [comment]
I think the issue is that `aws.sdk.kotlin:cognito:<version>` does not point to a valid artifact. 

As pointed out in the comment above the valid cognito libraries are one of:
* `aws.sdk.kotlin:cognitoidentity:<version>`
* `aws.sdk.kotlin:cognitoidentityprovider:<version>`

**Comment by tkhill-AWS** [comment]
[Fixed](https://code.amazon.com/packages/DocsSDKforKotlin/commits/b9686f58a0415bb443d70f21f130c7e4d57d6b3b). Changed to `cognitoidentityprovider` and deployed to public website.
