### ISSUE TITLE
RestXml error members are not always modeled correctly

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#479]
### Describe the bug

The `Message` member of errors in smithy needs special casing.

As an example the STS [InvalidIdentityTokenException](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.5-beta/codegen/sdk/aws-models/sts.2011-06-15.json#L897) has a member `message` but the actual response that comes back looks like this:

```xml
<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">
    <Error>
        <Type>Sender</Type>
        <Code>InvalidIdentityToken</Code>
        <Message>No OpenIDConnect provider found in your account for ...</Message>
    </Error>
    <RequestId>5045ca91-1234-567-8910-00a3c906be6c</RequestId>
</ErrorResponse>
```

Note the capitalization of `Message` vs the model `message`.

### Expected behavior

`InvalidIdentityTokenException.message` should contain the message from the response.

### Current behavior

Today the message field is correctly parsed by the XML error response [deserializer](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.5-beta/aws-runtime/protocols/aws-xml-protocols/common/src/aws/sdk/kotlin/runtime/protocol/xml/RestXmlErrorDeserializer.kt#L47) responsible for figuring out error code and other metadata before we parse the specific exception type.

This gets stashed into the `sdkErrorMetadata` so it is available with some digging, e.g.:
```kotlin
try {

}catch (ex: IdentityTokenException) {
    val metadataMessage = ex.sdkErrorMetadata.errorMessage
    // ideally it is available on the message directly
    val message = ex.message   // currently null
}
```

Ideally though it should also be parsed by the `InvalidIdentityTokenException` deserializer.

### Steps to Reproduce

Try to call `assumeRoleWithWebIdentity` using a JWT without having configured an OIDC provider in your account.

### AWS Kotlin SDK version used

0.9.5-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macos

**Comment by lauzadis** [comment]
This issue was fixed in [smithy-kotlin PR #1044](https://github.com/smithy-lang/smithy-kotlin/pull/1044/files#diff-fbccfc5a05be178f5e01a2fed7ffc70113cf3b4b8e1b37f5186f4948394627c3R152-R153). Verified this exception message is accessible in `ex.message` using the latest version of the SDK.
