### ISSUE TITLE
Add EBS Direct support

### ISSUE THREAD

**Issue by axelfontaine** [awslabs/aws-sdk-kotlin#482]
### Describe the feature

Extend the SDK to cover the [EBS Direct](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html)

### Is your Feature Request related to a problem?

Unable to access the EBS Direct APIs

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.9.5-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Win11 x64

**Comment by aajtodd** [comment]
@axelfontaine Could you expand on what is missing from the SDK? The [EBS API Actions](https://docs.aws.amazon.com/ebs/latest/APIReference/API_Operations.html) all look accessible from the Kotlin [EbsClient](https://docs.aws.amazon.com/sdk-for-kotlin/latest/reference/ebs/services/ebs/aws.sdk.kotlin.services.ebs/-ebs-client/index.html) (see [ebs artifact](https://search.maven.org/artifact/aws.sdk.kotlin/ebs/0.9.5-beta/jar)).

**Comment by axelfontaine** [comment]
My bad. I completely missed that. Sorry for the trouble.

**Comment by aajtodd** [comment]
> My bad. I completely missed that. Sorry for the trouble.

No trouble at all.
