### ISSUE TITLE
 Get S3 object via presign with Unicode name fails with signature mismatch

### ISSUE THREAD

**Issue by vcanuel** [awslabs/aws-sdk-kotlin#485]
### Describe the bug

I generate a presign Request containing a key with an Unicode character. Then I got an error when retrieve it via an HTTP client : 
`The request signature we calculated does not match the signature you provided. Check your key and signing method`

### Expected behavior

I should be able to retrieve the S3 file.

### Current behavior

I got an error : `The request signature we calculated does not match the signature you provided. Check your key and signing method`

### Steps to Reproduce

```
fun main(): Unit = runBlocking {
    val c = S3Client { region = "us-east-2" }

    try {
        println("Creating obj")
        c.putObject(PutObjectRequest.invoke {
            bucket = "test-bucket"
            key = "nameé.txt"
            body = ByteStream.fromString("abody")
        })

        println("Getting obj")
      val getRequest = GetObjectRequest {
            bucket = "test-bucket"
            key = "nameé.txt"
        }
        val signRequest =   getRequest.presign(c.config, 60L)

   CrtHttpEngine().use { engine ->
        val httpClient = sdkHttpClient(engine)
        val call = httpClient.call(signRequest)
        call.complete()
        println("status =  ${call.response.status}") // this returns  status =  403: Forbidden
    }

    } finally {
        c.close()
    }
}
```

### Possible Solution

I think this is the same root cause as this issue https://github.com/awslabs/aws-sdk-kotlin/issues/200

### Context

We have lot of files with Unicode characters it it.

### AWS Kotlin SDK version used

0.9.5-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac OS 12.0.1

**Comment by kggilmer** [comment]
Thank you for the clear and detailed bug report @vcanuel .  I've confirmed the issue in a test based on your work.  I'll update this ticket when a fix is available.

**Comment by kggilmer** [comment]
Hi @vcanuel , the fix for this issue was merged into the SDK today.  You will be able to get the fix in the next release of the SDK.
