### ISSUE TITLE
Support for Progress Listener

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#490]
### Describe the feature

Add support for Progress Listener on PutObjectRequest, GetObjectRequest and UploadPartRequest. Progress Listener is used to track progress for Upload and Download task from S3. 

### Is your Feature Request related to a problem?

Amplify SDK relies on this functionality to support progress tracking for S3 Transfer apis.

### Proposed Solution

[AWS Android SDK](https://github.com/aws-amplify/aws-sdk-android/blob/70032c3531f3dacf73148e1be31104d1dca334dc/aws-android-sdk-core/src/main/java/com/amazonaws/event/ProgressListener.java) support this functionality and could be used as reference.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.9.5-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 12

**Comment by brabo-hi** [comment]
Hi,
any update regarding this feature? it is implemented using the Java SDK, that would be nice to have it on the kotlin SDK too.
If not what other way can we listen upload progress ?

**Comment by aajtodd** [comment]
We have a [design](https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/interceptors.md#progress-listeners) in place for how we want to expose this. The design requires some other in-progress work to be usable on a per/request basis though.

**Comment by aajtodd** [comment]
Closing this as both pieces (interceptors + per/op config) are now available as of [0.20.0-beta](https://github.com/awslabs/aws-sdk-kotlin/releases/tag/v0.20.0-beta).


The way to do this is roughly as follows:

1. Create an interceptor that replaces the HTTP body with one that updates your progress listener every time data is read. I've left out a bunch of detail here, but you'll have to deal with various `ByteStream` variants. More than likely you would want a wrapper type per variant and match that to the actual underlying `builder.body` type and branch on that.

```kotlin
class AddUploadProgressListenerInterceptor(
    private val progressListener: ProgressListener
): HttpInterceptor {
    override suspend fun modifyBeforeTransmit(
        context: ProtocolRequestInterceptorContext<Any, HttpRequest>
    ): HttpRequest {
        val builder = context.protocolRequest.toBuilder()
        // wrap the body with a custom type that updates `progressListener` every time data is read
        // in practice you need to probably unwrap builder.body and have a progress listener type per/variant
        builder.body = ProgressListenerBody(builder.body, progressListener)
        return builder.build()
    }
}

```

2. Add this interceptor for specific operations, e.g.

```kotlin
val progressListener = ProgressListener(...)
val response = s3.withConfig { interceptors += AddUploadProgressListener(progressListener) }
    .use { s3WithListener ->
         // this operation will be carried out with the progress listener
         s3WithListener.putObject(...)
    }
```

It should look roughly the same for response bodies but with a different interceptor hook (e.g. `modifyBeforeDeserialization`). Start a discussion if you have questions on how to do any of this.

**Comment by Conjuror1279** [comment]
Hi @aajtodd, is there someplace where I can find a code sample for the ProgressListenerBody class, I am not able to understand how to add a progress listener in the above code. The function modifyBeforeTransmit is only called once and doesnot give me the progress about the upload. I've been stuck at this for quite a while and any help would be much appreciated. 

Also, is there a way to receive or generate the presigned url of the uploaded file using this kotlin sdk?

**Comment by sdhuka** [comment]
@Conjuror1279 You can look at the [Amplify source code](https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/ProgressListenerHttpInterceptor.kt) for both upload and download progress listener reference.

You can use pre-signed API similar to [this](https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.kt#L71)

**Comment by ianbotsf** [comment]
Hi @Conjuror1279, I see that you also opened a discussion (#926) and an issue (#922) for this. Have you been able to look at the links provided by @sdhuka and test them out?

**Comment by Conjuror1279** [comment]
Hi @sdhuka @ianbotsf. Thanks for your reply. I created a issue regarding this and was waiting for a response over there, not realizing that you had responded here. Anyways, I will try the method pointed out by you and see if it works. 

Thanks again for your help!

**Comment by Conjuror1279** [comment]
Hi, I tried the method suggested and it seems that the progress is always coming up to be 8192.0 bytes. I logged the bytes provided from the below code, they come out to be constant. This piece of code is executing multiple times but the bytes returned is always the same
return delegate.read(sink, limit).also {
                        if (it > 0) {
                            progressListener?.onProgress(it)
                        }
                    }

**Comment by sdhuka** [comment]
@Conjuror1279 thats correct, you have to add up the progress reported by the interceptor to calculate the overall progress, something similar to [this](https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/ProgressListener.kt#L107).

**Comment by lon9man** [comment]
Hello, found this discussion about ProgressListener, but can't find this classes in sources. is it actual functionality?

**Comment by lauzadis** [comment]
Hi @lon9man, the `ProgressListener` here refers to the [one implemented in Amplify's aws-android-sdk project](https://github.com/aws-amplify/aws-sdk-android/blob/70032c3531f3dacf73148e1be31104d1dca334dc/aws-android-sdk-core/src/main/java/com/amazonaws/event/ProgressListener.java). We don't offer one ourselves. Progress tracking and other utilities will be supported in [the S3 Transfer Manager high-level library](https://github.com/awslabs/aws-sdk-kotlin/issues/972). If you would benefit from this, please leave a +1 on that issue.
