### ISSUE TITLE
CrtHttpEngine leaks connections on cancellations

### ISSUE THREAD

**Issue by tavomaciel** [awslabs/aws-sdk-kotlin#511]
### Describe the bug

CrtHttpEngine currently tries to guarantee a connection is always closed with an `invokeOnCompletion` call, which tells the ResponseHandler to complete, which in turn closes the connection:
```
val conn = withTimeoutOrNull(config.connectionAcquireTimeout) {
            manager.acquireConnection()
} ?: throw ClientException("timed out waiting for an HTTP connection to be acquired from the pool")

val respHandler = SdkStreamResponseHandler(conn)
callContext.job.invokeOnCompletion {
    logger.trace { "completing handler; cause=$it" }
    // ensures the stream is driven to completion regardless of what the downstream consumer does
    respHandler.complete()
}
```
This implementation would be fine if there weren't any suspension points which could interrupt the coroutine between `manager.acquireConnection()` and `job.invokeOnCompletion`. But if you look closely at the definition of `manager.acquireConnection()`:

```
public actual suspend fun acquireConnection(): HttpClientConnection {
        val connFuture = jniManager.acquireConnection()
        val jniConn = connFuture.await()
        return HttpClientConnectionJVM(jniConn)
}
```

The connection request is made at `jniManager.acquireConnection()`. This is a [hot future](https://elizarov.medium.com/cold-flows-hot-channels-d74769805f9), whether the connection is taken or not it has been already been requested from the pool.
The problem is that awaiting for the connection itself IS a suspending point, and that allows the coroutine itself to be cancelled before the `invokeOnCompletion` hook is installed.

### Expected behavior

Canceling an AWS SDK request when it's waiting for connections should always return the connection.

### Current behavior

Cancelling coroutines running AWS requests may leak the connection and never return it to the pool.
Further requests after such leaks fail with
```
aws.sdk.kotlin.runtime.ClientException: timed out waiting for an HTTP connection to be acquired from the pool
 at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine.roundTrip(CrtHttpEngine.kt:85)
  at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine$roundTrip$1.invokeSuspend(CrtHttpEngine.kt)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Steps to Reproduce

In a simple Spring Boot project:

```
@Configuration
class DynamoDbConfig {
    @Bean fun ddbClient() = DynamoDbClient {}
}

@Component
class SomeDao(val dynamo: DynamoDbClient) {
   val random = Random()
    suspend fun putItem() {
        dynamo.putItem {
            tableName = "some-table"
            item = mapOf("SomeKey" to AttributeValue.S("some-value-${random.nextInt()}" ))
        }
    }
}

@RestController
@RequestMapping("/api/put-items")
class SomeResource(val someDao: SomeDao) {
    @PostMapping
    suspend fun putItems() {
        log.info("Persisting items...")
        coroutineScope { // This block will await untill all items are persisted
            repeat(100) {
                log.info("Launching persistItem $it...")
                launch { someDao.putItem() }
                log.info("Launched persistItem $it.")
                throw RuntimeException("Some random exception which will cancel all awaiting coroutines in scope")
            }
            log.info("Awaiting for persistItem results...")
        }
        log.info("All items persisted")
    }
}
```

Steps to reproduce:
- Request `POST /api/put-items` once.
- This will launch 100 PutItem requests to the dynamo client and await for them all.
- The first finishing request will throw an exception. The `coroutineScope` will cancel all awaiting operations (due to [Structured Concurrency](https://medium.com/@elizarov/structured-concurrency-722d765aa952)
- Request `POST /api/put-items` once again (or twice more)
- The request will block waiting for connections until it times out. No connection should be available as they weren't returned to the pool.

### Possible Solution

The easiest solution I see is wrapping the whole block that acquires connections in a `withContext(NonCancellable) { ... }` block. But this makes every request now required to at least wait for the connection before returning.
Preferably, a better way to notify the `jniManager` the connection wasn't used needs to be found.

### Context

This makes the use of Structured Concurrency very hard.

I want to be able to put multiple items in Dynamo at once, so launching it all in a scope seems like the obvious choice. But now that makes me worried one exception in a single coroutine could make all the others awaiting leak their connections.

### AWS Kotlin SDK version used

0.11.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macOS BigSur 11.6.2

**Comment by aajtodd** [comment]
@tavomaciel Thanks for the detailed report and explanation! We will take a look at getting this fixed. Using `NonCancellable` is (as you pointed out) probably not the right solution.
