### ISSUE TITLE
Kotlin 1.6 upgrade ~ Duration and Coroutine Test

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#513]
Acceptance Criteria
* Kotlin coroutine dependency updated from 1.5.x to 1.6.x release
* Update public APIs that use durations as integers to use Duration type

**Comment by kggilmer** [comment]
Blocking on windows-only regression in test case.  See https://github.com/awslabs/aws-sdk-kotlin/pull/514#discussion_r800711499  Further investigation required

**Comment by aajtodd** [comment]
closed by #514
