### ISSUE TITLE
ChatQL implementation 

### ISSUE THREAD

**Issue by masterofdaemon** [awslabs/aws-sdk-kotlin#541]
### Describe the feature

Is it possible to implement ChatQL feature in near future or it's in todo?
Or you can help me to figure out how to make efficient chat with low cost time

### Is your Feature Request related to a problem?

I have an idea of a KMM application with chat and choosing cloud for this, don't want to make a big server side code

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

beta.13

### Platform (JVM/JS/Native)

JVM/Native

### Operating System and version

Mac/Android/IOS

**Comment by aajtodd** [comment]
My understanding of "[ChatQL](https://aws.amazon.com/blogs/mobile/building-a-serverless-real-time-chat-application-with-aws-appsync/)" is that it's a starter web app/demo of using AppSync as the primary backend driver. 

@masterofdaemon Can you clarify what you would be looking for from the Kotlin SDK?

**Comment by aajtodd** [comment]
We don’t really have the expertise to help out here. This repository is specifically for issues and feature requests for the AWS SDK for Kotlin. I’d suggest asking your question on StackOverflow or AWS [re:Post](https://repost.aws)
