### ISSUE TITLE
Allow for Proxy Configuration

### ISSUE THREAD

**Issue by wasifaleem** [awslabs/aws-sdk-kotlin#551]
### Describe the feature

Allow connecting through a proxy server and configure proxy server settings (proxy host, port, and username/password).

### Is your Feature Request related to a problem?

Our org is behind a proxy and this feature will allow us to use aws kotlin sdk

### Describe alternative solutions or features you've considered

AWS Java SDK support proxy configuration.

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

v0.13.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

**Comment by ianbotsf** [comment]
Hi @wasifaleem, thanks for your feature request.

We have existing issue [smithy-kotlin#494](https://github.com/awslabs/smithy-kotlin/issues/494) to track adding proxy support and configuration. Please feel free to add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to that issue to help us prioritize.

Resolving in favor of [smithy-kotlin#494](https://github.com/awslabs/smithy-kotlin/issues/494).
