### ISSUE TITLE
Possible memory leak in new default HTTP engine

### ISSUE THREAD

**Issue by cprice404** [awslabs/aws-sdk-kotlin#587]
### Describe the bug

We have a long-running server application that uses the AWS kotlin SDK.  One of the things that it does is to instantiate a long-lived SQS client at startup, and poll it to check for new messages periodically.

We have been running in production on `v0.10.1-beta` of the AWS kotlin SDK for quite some time with no issues.  Yesterday, we upgraded to `v0.14.1-beta`.  Shortly thereafter we began to see OOMs killing our service.

Inspecting our heap dumps, we see the vast majority of the memory (well over 300MB out of a 450MB max heap) consumed by the SQS client.  Digging in to the object reference, all of the memory is held by the ktor Http engine.

I reviewed your changelog and the obvious suspect is https://github.com/awslabs/aws-sdk-kotlin/pull/554 .

Our DynamoDB client also shows up with very high memory usage (> 100MB) in the heap dumps with `v0.14.1-beta`.

Reverting to `v0.10.1-beta` and monitoring the service carefully, heap dumps are back to showing the SQS and DDB clients as using only a trivial amount of memory, and the CRT http engine only shows up as consuming around 1kb.

### Expected behavior

Long-lived AWS SDK client objects should not leak memory over time.

### Current behavior

Long-lived AWS SDK client objects appear to be leaking memory through the ktor HTTP engine.

### Steps to Reproduce

Create an SQS client with v0.14.1-beta of the SDK.  Keep it open for a long time, polling `receiveMessage` on it at some interval.  Take periodic heap dumps and observe increased memory usage over time.

### Possible Solution

Revert to previous HTTP engine?  Or perhaps the new engine is not closing some stream that it needs to be closing.

### AWS Kotlin SDK version used

v0.14.1-beta , v0.10.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Amazon Linux 2 and OSX

**Comment by aajtodd** [comment]
Thanks for the bug report. I'll take a look and dive into this (I may have some follow up questions).


As an FYI in the meantime if you needed/wanted to upgrade for other reasons you could do so and keep using the existing CRT engine. You just have to add the [dependency](https://search.maven.org/artifact/aws.smithy.kotlin/http-client-engine-crt/0.8.3/jar) and manually override the default HTTP engine when constructing the client.

```kotlin
import aws.smithy.kotlin.runtime.http.engine.crt.CrtHttpEngine

val crtEngine = CrtHttpEngine()
val sqs = SqsClient { 
    ...
    httpClientEngine = crtEngine
}

...

sqs.close()
crtEngine.close()
```

**Comment by cprice404** [comment]
Thanks.  I did try that opt-out path and it didn't seem to work for me, but it's entirely possible that I made a mistake.

Will keep that in mind but we are likely to just try to stay pinned to an older version of the SDK until this is triaged.  Appreciate your looking into it!

**Comment by aajtodd** [comment]
@cprice404 

I'm not able to reproduce this yet.

Could you share a bit more detail:
* what JVM distribution and version are you using
* what polling interval
* rough size of a message being processed
* what kind of throughput are we talking about here
* are you launching a coroutine per/poll or is this some long lived coroutine that runs in the background polling
* how fast is memory leaking

Anything else you can share would be helpful in tracking this sort of issue down.

>  I did try that opt-out path and it didn't seem to work for me,
I'm also interested to hear more on what you mean by this. As in you couldn't get it to work/compile or it didn't solve this memory issue?

**Comment by cprice404** [comment]
> @cprice404
> 
> I'm not able to reproduce this yet.
> 
> Could you share a bit more detail:
> 
>     * what JVM distribution and version are you using

In our production environment we are running via the amazoncorretto:17 docker image, on AL2.
But I was able to repro the same behavior on my mac, intel, OpenJDK 17.0.1.

>     * what polling interval

we poll, `delay` for 1 second, then poll again.

>     * rough size of a message being processed

< 1kb

>     * what kind of throughput are we talking about here

There is a single background thread making these requests, so it's <= 1 SQS Api call per second.

>     * are you launching a coroutine per/poll or is this some long lived coroutine that runs in the background polling

Long-lived coroutine, running on a fixed thread pool executor, with `delay`s between the API calls.

>     * how fast is memory leaking

With a heap size of 450MB, the servers would reliably OOM somewhere between 4-5 hours after launch.
The increased memory consumption was observable in heap dumps on my mac within 1 hour, perhaps even by the 30 minute mark.  Definitely the memory footprint of the SQS and DDB clients on my mac after 30 minutes was markedly different when I was running with `0.10.1-beta` vs `0.14.1-beta`.

> 
> Anything else you can share would be helpful in tracking this sort of issue down.

99% of the requests through the SQS client in prod yielded 0 messages; 100% on my mac yielded 0 messages.  Just mentioning that to point out that I don't think the SQS message payload size is probably relevant here.

Also just want to call out that the increased memory usage was also very visible in the DDB client, not just the SQS client.  I focused on the SQS client in the bug report because (1) it was consuming more memory, and (2) our consumption of the DDB client is less predictable since it depends on our service's incoming traffic, whereas the SQS client was entirely predictable since it is just scheduled polling and no relationship to our service's incoming traffic.

> 
> > I did try that opt-out path and it didn't seem to work for me,
> 
> I'm also interested to hear more on what you mean by this. As in you couldn't get it to work/compile or it didn't solve this memory issue?

It compiled but then when I did heap dumps during the run, I was still seeing the ktor engine in the object hierarchy, dominating the memory usage.  HOWEVER, I was doing some hacky things to cobble together the `java` CLI args/classpath in order to be able to run it through my profiler, so it is possible that I just screwed up the CLI args and referenced an older jar or something.  I just ran out of time to fix the production issue at that point and felt that jumping back to 0.10.1 was safer.

**Comment by cprice404** [comment]
Here's a screenshot from the profiler for a heap dump that I took during a run on my mac:

![Screen Shot 2022-04-15 at 10 42 20 AM](https://user-images.githubusercontent.com/1341071/163603346-84501b3d-4c06-40b0-83f9-fe2a1de22894.png)

**Comment by cprice404** [comment]
Corresponding heap dump for another run on my mac after reverting to 0.10.1.  Zero changes to our code other than reverting the AWS SDK version.

![Screen Shot 2022-04-15 at 10 45 20 AM](https://user-images.githubusercontent.com/1341071/163603606-0468a2a8-b015-4573-a612-bf55a6549b02.png)

**Comment by aajtodd** [comment]
>  I just ran out of time to fix the production issue at that point and felt that jumping back to 0.10.1 was safer

Totally makes sense.

>  I was still seeing the ktor engine in the object hierarchy, dominating the memory usage

Interesting. We still use the default engine for credential providers because a user supplied engine isn't threaded through everywhere (this is something we want to fix at some point so that if you give a client a custom HTTP engine it used consistently by all components).

Thank you very much for the detailed information! I'll update here when I have anything.

**Comment by cprice404** [comment]
Here is a minimal reproducer:

https://github.com/cprice404/kotlin-aws-sdk-ktor-leak

After running that for about an hour on my mac, the ktor engine was up to about 65MB of memory consumption:

<img width="1438" alt="Screen Shot 2022-04-16 at 10 15 50 AM" src="https://user-images.githubusercontent.com/1341071/163688237-bc233ae0-d44b-4086-9dbc-1e7d07de19f9.png">

**Comment by aajtodd** [comment]
Thanks! I was actually able to reproduce it Friday afternoon with your additional information. I think I know what is happening as well but need to spend a little more time with it. Will update here once I confirm and hopefully have a fix shortly after sometime this week.

**Comment by aajtodd** [comment]
Fix should go out in next release (most likely `0.14.4-beta`) later this week.

**Comment by cprice404** [comment]
Just to close the loop on this - I ran our reproducer with v0.14.4-beta and it does indeed appear to have fixed the issue.
