### ISSUE TITLE
SPDX License Identifier has unnecessary '.'

### ISSUE THREAD

**Issue by hyandell** [awslabs/aws-sdk-kotlin#601]
### Describe the bug

The source  code for the Kotlin SDK has an SPDX License Identifier of:

` * SPDX-License-Identifier: Apache-2.0.`

Could that extra '.' be removed? It is not part of the identifier spec to treat that line like a sentence and so will mean any tooling has to add additional logic to remove the '.', which given '.' is typically in versioning strings is also a bit uncomfortable to go ignoring.

### Expected behavior

Not having the '.'

### Current behavior

Having the '.'

### Steps to Reproduce

Viewing the source.

### AWS Kotlin SDK version used

0.15.0

### Platform (JVM/JS/Native)

n/a

### Operating System and version

n/a

**Comment by lucix-aws** [comment]
This was addressed in #678, awslabs/smithy-kotlin#687, and awslabs/aws-crt-kotlin#54
