### ISSUE TITLE
Jars are empty starting at 0.16.0

### ISSUE THREAD

**Issue by vgiguere** [awslabs/aws-sdk-kotlin#626]
### Describe the bug

It looks like you have been releasing empty jars starting with version 0.16.0 on some maven repositories.

core, dynamodb and others are now a few bytes and there are no classes inside.

Good: https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb/0.15.0/
Bad:   https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb/0.16.0/

### Expected behavior

self explanatory

### Current behavior

Jars starting 0.16.0 have no classes in them

### Steps to Reproduce

Update maven dependency in a pom.xml to 0.16.0 or 0.16.0beta1 and try compiling an application. 
All classes are missing if you get those libs from public maven repositories.

Working
https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb/0.15.0/

Not Working
https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb/0.16.0/

### Possible Solution

- Build process is broken?
- Release process is broken?
- Maven repository screwed up something?

### Context

It's blocking me from using the latest version of the lib 

### AWS Kotlin SDK version used

0.16.0 , 0.16.1.beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac OSX 12.3.1

**Comment by lucix-aws** [comment]
Thanks for reporting this.

As of [0.16.0](https://github.com/awslabs/aws-sdk-kotlin/blob/main/CHANGELOG.md#0160---05262022), we've switched to Kotlin Multiplatform builds for AWS service clients. This results in splitting the "common" artifacts from the platform specific ones (e.g. JVM).

So, dynamodb is now vendored at
* [common](https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb/0.16.0/)
* [jvm](https://repo1.maven.org/maven2/aws/sdk/kotlin/dynamodb-jvm/0.16.0/)

This change should be transparent to Gradle users using either the `kotlin("jvm")` or `kotlin("multiplatform")` plugin.

How are you consuming the SDK as a dependency (e.g. gradle? maven? etc).
It may be that you just need to consume the -jvm artifact(s) now explicitly.

**Comment by vgiguere** [comment]
I was consuming them as with previous versions and bumping the version when there were new released.
I not noticed the change.

Previous config:

```
 <dependency>
      <groupId>aws.sdk.kotlin</groupId>
      <artifactId>dynamodb</artifactId>
      <version>${aws-sdk-kotlin.version}</version>. 
    </dependency>

 ```
 
 
 I have changed to :
 
 ```
  <dependency>
      <groupId>aws.sdk.kotlin</groupId>
      <artifactId>dynamodb</artifactId>
      <version>${aws-sdk-kotlin.version}</version>. 
    </dependency>

 ```
 
 And now it works.
 
 
 Thank you  :)
