### ISSUE TITLE
`getCredentialsForIdentity` returns incorrect expiration

### ISSUE THREAD

**Issue by div5yesh** [awslabs/aws-sdk-kotlin#665]
### Describe the bug

When calling getCredentialsForIdentity the expiration is not returned properly by the SDK. The expiration when converted to epochSeconds returns 1 which is year 1970. 

### Expected behavior

Client should return expiration that points to current timestamp.

### Current behavior

Expiration points to year 1970 and epochSeconds is 1.

### Steps to Reproduce

Call `cognitoIdentityClient.getCredentialsForIdentity`.

### Possible Solution

The conversion to Instant should multiply expiration by 1000 before converting to Instant to get correct timestamp.

### AWS Kotlin SDK version used

0.16.3-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 10

**Comment by ianbotsf** [comment]
Cognito's raw API response includes expiration seconds in scientific notation, such as `1.659377625E9`. Our current parser only searches for digits and the decimal dot and ignores anything after the `E`, thus reading a number smaller than 10.

**Comment by ianbotsf** [comment]
OK, I've verified a change that allows a `getCredentialsForIdentity` call to return a correct expiration value. The change is reviewed and pushed to main. It should be present in this week's release.
