### ISSUE TITLE
ConfigService batchGetResourceConfig returns incorrect resourceCreationTime

### ISSUE THREAD

**Issue by davjhan-doordash** [awslabs/aws-sdk-kotlin#666]
### Describe the bug

When using the Kotlin API:

```
// identifiers: List<ResourceIdentifier>
 val result = client.batchGetResourceConfig(
            BatchGetResourceConfigRequest {
                resourceKeys = identifiers.map {
                    ResourceKey {
                        resourceId = it.resourceId
                        this.resourceType = it.resourceType
                    }
                }
            }
        )
```
        
Printing `result.baseConfigurationItems.map{ it.resourceCreationTime }` gives **for all entries**

```
1970-01-01T00:00:01.550006Z
```

Which basically means EpochSecond = 1.

### Expected behavior

When using the aws cli, 

```
aws configservice batch-get-resource-config --resource-keys resourceType=AWS::AutoScaling::AutoScalingGroup,resourceId=<the arn>
```

I see

```
{
...
    "resourceCreationTime": "2020-05-04T14:25:47.457000-07:00",
...
}
```
            
            Which is expected. I can also confirm it through the console UI. I can also confirm that the resource was not created in 1970. 😅

### Current behavior

resourceCreationTime is always

 ```
1970-01-01T00:00:01.550006Z
```

### Steps to Reproduce

Just call batchGetResourceConfig like usual.

```
// identifiers: List<ResourceIdentifier>
 val result = client.batchGetResourceConfig(
            BatchGetResourceConfigRequest {
                resourceKeys = identifiers.map {
                    ResourceKey {
                        resourceId = it.resourceId
                        this.resourceType = it.resourceType
                    }
                }
            }
        )
```

### Context

We use this API at DoorDash to keep tabs on our infrastructure. This is critical and is a blocker to us using the Kotlin SDK.

### AWS Kotlin SDK version used

0.17.0-beta
Also tested: 0.17.2-beta
### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOs Monterey 12.4 (21F79)

**Comment by ianbotsf** [comment]
Hi @davjhan-doordash, thanks for your bug report. I've reproduced the problem using your code as a starting point and this is the same issue reported in #665, the fix for which has been pushed to **main** and will be released later today.
