### ISSUE TITLE
Implement static stability support for credentials providers

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#707]
### Describe the feature

TBD

### Is your Feature Request related to a problem?

n/a

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.17.6-beta

### Platform (JVM/JS/Native)

Any

### Operating System and version

Any

**Comment by lauzadis** [comment]
Closed by #719
