### ISSUE TITLE
Plumb explicit HTTP engine and region through credential provider chain

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#711]
### Describe the feature

If a user sets a custom `httpClientEngine` on their service client config we don't currently plumb this through to the credential provider chain.

```kotlin
interface S3Client {
     ...

    public class Config private constructor(builder: Builder): HttpClientConfig, SdkClientConfig {
        public val credentialsProvider: CredentialsProvider = builder.credentialsProvider?.borrow() ?: DefaultChainCredentialsProvider()
        ...
        override val httpClientEngine: HttpClientEngine? = builder.httpClientEngine
     }
      ...
```

This appears to also be true for `region`

### Is your Feature Request related to a problem?

N/A

### Proposed Solution

N/A

### Describe alternative solutions or features you've considered

N/A

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

N/A

### Platform (JVM/JS/Native)

N/A

### Operating System and version

N/A

**Comment by lauzadis** [comment]
Closed by #730 and [awslabs/smithy-kotlin/721](https://github.com/awslabs/smithy-kotlin/pull/721)
