### ISSUE TITLE
chore: remove trailing # from "Issue" section in PR template

### ISSUE THREAD

**Issue by lauzadis** [awslabs/aws-sdk-kotlin#717]
### Describe the issue

There is a [trailing `#` in the PR template](https://github.com/awslabs/aws-sdk-kotlin/blob/main/.github/pull_request_template.md?plain=1#L3) that I don't think should be there.

Currently:

```
## Issue \#
```

Proposed:
```
## Issue
```

### Steps to Reproduce

N/A

### Current behavior

N/A

### AWS Kotlin SDK version used

N/A

### Platform (JVM/JS/Native)

N/A

### Operating System and version

N/A

**Comment by ianbotsf** [comment]
I'm pretty sure this `#` is here to encourage submitters to add the issue _number_ rather than a text description of the issue. If the existing title is unclear, perhaps we should replace this with "Issue number" or something similar.

**Comment by lauzadis** [comment]
Ah that makes sense, it was being weirdly formatted  on my editor and I didn't understand the purpose for it.
