### ISSUE TITLE
Replace all legacy logging with tracing framework log events

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#757]
Once [the tracing framework](https://github.com/awslabs/smithy-kotlin/issues/677) is merged, all instances of legacy logging code should be replaced with logging via trace spans. Specifically, `KotlinLoggingAdapter` and `Logger.getLogger` should be removed. Code that was using them should be updated to get a `Logger` from the active `CoroutineContext` (or directly from a `TraceSpan`). This may involve passing coroutine context or trace spans into code that don't currently have access to them (but do require logging facilities).

**2023-06-05 Update**: This is on hold while tracing framework design is being rethought. Once we decide on design updates (or decide to leave in place the current decide) then we can re-prioritize this work.

**Comment by mdaif** [comment]
Hi,
I'm looking for a new challenge in Kotlin, and I'd be happy to pick this up as my first task. I've checked the open PRs and I didn't find a PR to address this issue. I assume this is still needed ?

**Comment by ianbotsf** [comment]
Hi @mdaif, thanks for volunteering to work on this issue. Unfortunately, right now we're in the middle of rethinking our tracing design and we may make changes to it. We're holding off implementing the replacement of legacy logging until we get that design updated. I recommend you do not submit a PR for this since it might involve throwaway work.

I'll update the issue description accordingly!

**Comment by ianbotsf** [comment]
#940 now captures our intent to redesign the tracing framework. This task is blocked until #940 is complete.

**Comment by aajtodd** [comment]
This work was completed with the tracing API refactor
