### ISSUE TITLE
DynamodDB Enhanced Client Design

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#76]
Consider implementing an "enhanced" DDB client like offered by [Java](https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/)

Some considerations:
* We might be able to do this as a compiler plugin and generate rather optimized code so that we don't have to rely on annotation processing (which I believe is JVM only at the moment) OR on reflection capabilities.

**Comment by ianbotsf** [comment]
Resolving in favor of #472.
