### ISSUE TITLE
Can't import aws.sdk.kotlin using Maven

### ISSUE THREAD

**Issue by david-kubecka** [awslabs/aws-sdk-kotlin#760]
### Describe the bug

My project has a dependency on the latest version of the S3 SDK:
```
        <dependency>
            <groupId>aws.sdk.kotlin</groupId>
            <artifactId>s3</artifactId>
            <version>0.17.12-beta</version>
        </dependency>
```
The library can be successfully downloaded from Maven Central (as seen in the Dependency Analyzer) but no class can be imported from the library:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1436135/203088682-a471d6a1-a81d-4879-a426-ae8adac69672.png">

### Expected behavior

Classes can be imported.

### Current behavior

Classes can't be imported.

### Steps to Reproduce

- include AWS S3 SDK into your pom.xml
- try to import any class, e.g. `aws.sdk.kotlin.services.s3.S3Client`

### AWS Kotlin SDK version used

0.17.12-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

MacOS 12.4

**Comment by ianbotsf** [comment]
Thank you for the issue, @david-kubecka. The AWS SDK for Kotlin is a KMP project with separate artifacts for each supported platform. In the case of JVM, you'll need to pull in the artifact **s3-jvm** (not **s3**):

```xml
dependency>
    <groupId>aws.sdk.kotlin</groupId>
    <artifactId>s3-jvm</artifactId>
    <version>0.17.12-beta</version>
</dependency>
```

Did you find published documentation that (incorrectly) states **s3** is the artifact ID?

**Comment by ianbotsf** [comment]
Then we should probably publish guidance on how to use the SDK from Maven (and not just Gradle). I'll work with our internal docs team to get something out.

**Comment by david-kubecka** [comment]
Yes, that would be a good thing! Should I then close this issue? (I can import the JVM specific artifacts.)

**Comment by aajtodd** [comment]
Yes let's go ahead and close this one and we'll continue working to get better documentation w.r.t to maven in place. Thanks!

**Comment by ianbotsf** [comment]
To follow up: the [**Create a project file** section](https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/setup.html#setup-create-projet-file) of our **Set up** guide now includes an example of Maven configuration.
