### ISSUE TITLE
Feature: Provide a version catalog

### ISSUE THREAD

**Issue by trevjonez** [awslabs/aws-sdk-kotlin#805]
### Describe the feature

Gradle version catalogs can be published for external consumers. Having a aws-sdk-kotlin catalog would be a HUGE improvement for discoverability.

https://docs.gradle.org/current/userguide/platforms.html#sec:version-catalog-plugin

### Is your Feature Request related to a problem?

N/A - quality of life request

### Proposed Solution

Publish an official catalog for consumers to depend on explicitly.

### Describe alternative solutions or features you've considered

Do it by hand and suffer thru the maven central search to see what is or isn't supported instead of having auto complete options in your IDE

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Kotlin SDK version used

N/A

### Platform (JVM/JS/Native)

N/A

### Operating System and version

N/A

**Comment by ianbotsf** [comment]
Thanks for the feature request @trevjonez, this is an interesting idea. We'll take a look and see what it would take to support a published version catalog of our own.
