### ISSUE TITLE
Support for S3 accelerate mode 

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#810]
### Describe the feature

AWS Kotlin SDK is missing support for [acceleration mode](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-examples.html) with AWS S3. 

### Is your Feature Request related to a problem?

This feature was supported by [AWS Android SDK](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java#L140) and a blocker for Amplify customer to onboard onto v2.0

### Proposed Solution

NA

### Describe alternative solutions or features you've considered

Not available.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.17.12-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

**Comment by aajtodd** [comment]
Is [this](https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/-s3-client/-config/-builder/enable-accelerate.html) not what you are looking for? Or are you saying it doesn't work?

**Comment by sdhuka** [comment]
Thanks @aajtodd. I was checking in 0.17 and it was not available, will test it and update here.

**Comment by sdhuka** [comment]
Confirmed that S3 acceleration mode works as expected.
