### ISSUE TITLE
S3 needs {RequestRoute} path filtering to prevent duplication in requests

### ISSUE THREAD

**Issue by lucix-aws** [awslabs/aws-sdk-kotlin#815]
### Describe the bug

We need to filter the `{RequestRoute}` path prefix (on the `endpoint` trait) out of the model, as this is now handled by endpoints 2.0. Currently this only affects the `WriteGetObjectResponse` method. In its current state it may be duplicated on outgoing requests.

### Expected behavior

Make a `WriteGetObjectResponse` call, the request should complete normally.

### Current behavior

May fail due to an invalid hostname because of a duplicated `RequestRoute`.

### Steps to Reproduce

n/a

### AWS Kotlin SDK version used

0.19.2

### Platform (JVM/JS/Native)

n/a

### Operating System and version

n/a

**Comment by AnneMayor** [comment]
I am gonna fix it. Keep that in mind 🙂

**Comment by ianbotsf** [comment]
We'd welcome a PR on this if you feel like tackling it @AnneMayor. See our [contributing guidelines](https://github.com/awslabs/aws-sdk-kotlin/blob/main/CONTRIBUTING.md) for pointers on getting started.

**Comment by lauzadis** [comment]
Hi @AnneMayor! We were wondering if you had a chance to work on this issue? Since it's a bug that may affect users, we are planning to complete it soon and don't want to duplicate efforts if you've worked on it already.

**Comment by AnneMayor** [comment]
Thanks a lot :+1:
