### ISSUE TITLE
Use Sealed Classes for error handling instead for Exception

### ISSUE THREAD

**Issue by teimatinimarin** [awslabs/aws-sdk-kotlin#833]
### Describe the feature

Try/Catch and Exceptions is not the most 'kotlin natural' way to handle errors.
Use Sealed Classes instead.

### Is your Feature Request related to a problem?

AWS SDK for kotlin not feeling natural for Kotlin dev.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.20.

### Platform (JVM/JS/Native)

JVM

### Operating System and version

All

**Comment by ianbotsf** [comment]
The AWS SDK for Kotlin intentionally uses exceptions for error handling. While there are pros and cons of both exceptions and sealed class hierarchies, we opted to follow the style used in Kotlin stdlib and other popular libraries to provide a familiar error handling experience for users.

That said, if you prefer errors modeled in sealed classes then you may consider wrapping client calls in your own helper methods:

```kotlin
sealed interface S3CreateBucketOutcome {
    data class Success(val response: CreateBucketResponse) : S3CreateBucketOutcome
    data class BucketAlreadyExistsError(val message: String) : S3CreateBucketOutcome
    data class IoError(val message: String) : S3CreateBucketOutcome
    // ...
    data class UnknownError(val message: String) : S3CreateBucketOutcome
}

suspend fun createBucket(s3: S3Client, name: String): S3CreateBucketOutcome = runCatching {
    val response = s3.createBucket { bucket = name }
    S3CreateBucketOutcome.Success(response)
}.getOrElse { ex -> when (ex) {
    is BucketAlreadyExists -> S3CreateBucketOutcome.BucketAlreadyExistsError(ex.message!!)
    is IOException -> S3CreateBucketOutcome.IoError(ex.message!!)
    // ...
    else -> S3CreateBucketOutcome.UnknownError(ex.message!!)
}}
```
