### ISSUE TITLE
Failed to set Endpoint via EndpointProdiver or endpointUrl in S3Client

### ISSUE THREAD

**Issue by hantsy** [awslabs/aws-sdk-kotlin#842]
### Describe the bug

I tried to update my codes to use the latest AWS SDK Kotlin 0.20.1-beta, found the `endpointResolver` is removed.

I have tried to used the following two approaches to set endpoint, but failed.

```kotlin 
S3Client {
       // other config.
        endpointProvider = properties.endpoint?.let { url ->
            EndpointProvider { params ->
                Endpoint(url)                }
        }
}
```

or set it via `endpointUrl`.

```kotlin 
S3Client {
       // other config.
        endpointUrl = properties.endpoint?.let { Url.parse(it) }
}
```

The `properties.endpoint` is http://localhost:4566/ in local testing env.

### Expected behavior

It should work as `EndpointResolver`.  The old config worked well in a previous version.

```kotlin 
 endpointResolver = properties.endpoint?.let {
            StaticEndpointResolver(
                AwsEndpoint(it)
            )
       }
```

### Current behavior

I got the exception like this when calling the S3Client in my codes.

```bash 
	error=exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT /
```

### Steps to Reproduce

I used a localstack to mock all AWS locally, so I need to setup the endpoint to http://localhost:4566

### AWS Kotlin SDK version used

0.20.1-beta

### Platform (JVM/JS/Native)

Java 17

### Operating System and version

Windows 10

**Comment by lauzadis** [comment]
Hi, I was able to reproduce this. Our recent Endpoints 2.0 update had to change some things regarding bucket names in the request URL. We strip the bucket names from URLs due to how S3 parses them internally. That is the reason why you are getting the `PUT /` error, the bucket name is being stripped from the request.

To fix this you have to use `endpointUrl` and configure `forcePathStyle` to `true` 

1.
```kotlin
S3Client {
       // other config.
        endpointUrl = properties.endpoint?.let { Url.parse(it) }
        forcePathStyle = true
}
```

**Comment by hantsy** [comment]
Yes, my endpoint does not included a bucket name, the bucket name is configured by another property.

**Comment by hantsy** [comment]
Adding `forcePathStyle = true` make my tests work again on local machine.

But in my original config, endpoint is optional, only for the localstack for testing purpose.

Not sure this property(`forcePathStyle = true`) will affect the production config(only use AWS credential and bucket name, no endpoint there).

**Comment by hantsy** [comment]
If put the bucket name on the url, that means there is no need to set bucketname in the s3 operations?

I have checked the examples in this repo and the official doc https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/kotlin_s3_code_examples.html, there is no examples demos how to build a S3 Client using the new Endpoint.

**Comment by NikolayMetchev** [comment]
@lucix-aws Hi, in the latest version of the AWS SDK `forcePathStyle` has been removed (https://github.com/awslabs/aws-sdk-kotlin/commit/f6502eb10273ea70bc33712d0d350c1c472266ff) which is a workaround mentioned https://github.com/awslabs/aws-sdk-kotlin/issues/842#issuecomment-1426140171 
Is this workardoung no longer required?

**Comment by hantsy** [comment]
Updated to 0.35.0-beta, use `forcePathStyle`, it does not work as expected, I also post a question on discussions.
