### ISSUE TITLE
ReceiveMessageRequest.attributeNames is wrongly typed

### ISSUE THREAD

**Issue by TheFlow0360** [awslabs/aws-sdk-kotlin#857]
### Describe the bug

`ReceiveMessageRequest.attributeNames` has the type `List<QueueAttributeName>?`. Because of this, the actual values that are possible for this (that are even described in the functions documentation) aren't available. As a concrete example, there is no way to get the "SentTimestamp" Message Attribute directly, a possible workaround would be to use `QueueAttributeName.All` but will results in downloading attributes I'm not interested in.

### Expected behavior

There should be a type like `AttributeName` (`MessageAttributeName` would be bad because messageAttributes and attributes are two different things on a SQS Message) which is used for the `ReceiveMessageRequest.attributeName` list generic type, so that the actual allowed values can be passed to the request.

### Current behavior

You can only pass queue attribute names instead of attribute names available on SQS messages. The code documentation refers to values that you can't assign there.

### Steps to Reproduce

```
SqsClient { region = myRegion }.receiveMessage {
    queueUrl = sqsUrl
    waitTimeSeconds = 20
    maxNumberOfMessages = 10
    attributeNames = listOf(QueueAttributeName.All) // here I actually just want to use "TimestampSent"
}
```

### AWS Kotlin SDK version used

0.20.3-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Ubuntu 20.04 on WSL 2

**Comment by aajtodd** [comment]
> the actual values that are possible for this (that are even described in the functions documentation) aren't available.

AWS SDKs are all generated from a model. In this case the [ReceiveMessage.attributeNames](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/sdk/aws-models/sqs.json#L2601) targets the shape [AttributeNameList](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/sdk/aws-models/sqs.json#L1213) which is a list of [QueueAttributName](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/sdk/aws-models/sqs.json#L2425). This is why the name is `QueueAttributeName`. 

----

As to what you are trying to do I have to admit I had to play around with this to get it to work. The documentation for the [ReceiveMessage request parameters](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestParameters) indeed lists a handful of attributes including `SentTimestamp`. Immediately below that it lists the valid values which does not include most of the preceding names listed (the valid values do match the modeled enum values linked above though).

The values listed in the docs you are interested in seem to correspond with [MessageSystemAttributeName enum](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/sdk/aws-models/sqs.json#L2256) ([API ref docs](https://sdk.amazonaws.com/kotlin/api/latest/sqs/aws.sdk.kotlin.services.sqs.model/-message-system-attribute-name/index.html)). 


I've created a ticket internally to either update the model or documentation. In the meantime you can provide values that are not modeled by using `QueueAttributeName.fromValue`. Here is an example of getting just the `SentTimestamp`

```kotlin

import aws.sdk.kotlin.services.sqs.SqsClient
import aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName
import aws.sdk.kotlin.services.sqs.model.QueueAttributeName
import aws.sdk.kotlin.services.sqs.receiveMessage
import kotlinx.coroutines.*

const val QUEUE_URL = "<my-queue-url>"

fun main(): Unit = runBlocking {
    SqsClient.fromEnvironment().use { sqs ->
        val resp = sqs.receiveMessage {
            queueUrl = QUEUE_URL
            attributeNames = listOf(
                QueueAttributeName.fromValue(MessageSystemAttributeName.SentTimestamp.value)
            )
            waitTimeSeconds = 2
        }

        println("attributes:")
        println(resp.messages!![0].attributes)
    }
}
```

Output:

```
attributes:
{SentTimestamp=1677073570750}
```

internal: `V841124522`

**Comment by TheFlow0360** [comment]
I switched over to the Java SDK as this here is still beta and I need it for production. There I also noticed this problem exists in the Java v2 SDK as well. The MessageSystemAttributeName is something I found there as well because in the Java SDK, the keys of .attributes are typed like this - that's not the case in the Kotlin SDK, here it's just string keys.
Anyways, thanks a lot for the quick response! The workaround with QueueAttributeName.fromValue sadly doesn't work on the java side, here it is restricted to the known values.

**Comment by TheFlow0360** [comment]
Oh and one remark regarding this: 
> I've created a ticket internally to either update the model or documentation

The documentation is right, so the model needs to be changed. QueueAttributeName contains keys related to the SQS itself, not the message. When receiving messages these are not relevant, instead one should provide values described by MessageSystemAttributeName.

**Comment by RanVaknin** [comment]
This was fixed on 5/8/24.
