### ISSUE TITLE
Review codebases for use of experimental APIs

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#860]
In a few places our code uses Kotlin APIs marked as experimental or unstable. We should review all usages of thusly-marked APIs and determine if there's a path off of them to more stable implementations _before_ GA. All repositories should be reviewed.

In scope are _at least_ the following annotations:
* `@DelicateCoroutinesApi`
* `@ExperimentalContracts`
* `@ExperimentalCoroutinesApi`
* `@ExperimentalStdlibApi`
* `@ExperimentalTime`
* `@ExperimentalUnsignedTypes`
* `@FlowPreview`
* `@InternalCoroutinesApi`

Successful outcome of this task would be, for each instance of using APIs marked as experimental/unstable, one of the following resolutions:
* Plan to migrate away to new API or implementation
* Continue using with justification (e.g., usage is in low-risk area like tests or codegen)

**Comment by lauzadis** [comment]
> kotlin.time is in [focus](https://youtrack.jetbrains.com/issue/KT-52601?_gl=1*1agjs6r*_ga*MTQ4NDEwNjA2NC4xNjgzODIxNjE0*_ga_9J976DJZ68*MTY4ODA1MDkxMi4xMi4wLjE2ODgwNTA5MTIuNjAuMC4w&_ga=2.243413125.1415954567.1688050913-1484106064.1683821614) for stabilization, hopefully this stabilizes soon...

Based on [this changelog](https://kotlinlang.org/docs/eap.html#build-details) it should be coming in 1.9.0, I asked in KotlinLang Slack and they said "Yes. This includes time sources, time marks, and measureTime functions"

**Comment by aajtodd** [comment]
Closing as I believe this work was completed (see linked PRs)
