### ISSUE TITLE
progress listener for upload

### ISSUE THREAD

**Issue by Conjuror1279** [awslabs/aws-sdk-kotlin#922]
### Describe the issue

Hi, This is in reference to the issue #490. Is there someplace where I can find a code sample for the ProgressListenerBody class, I am not able to understand how to add a progress listener in the above code. The function modifyBeforeTransmit is only called once and doesnot give me the progress about the upload. I've been stuck at this for quite a while and any help would be much appreciated.

Also, is there a way to receive or generate the presigned url of the uploaded file using this kotlin sdk?

### Steps to Reproduce

- Not able to add progress listener to putObject in S3 kotlin sdk
- Not able to find any function to receive or generate the presigned url of the uploaded file.

### Current behavior

Adding a listener to the builder.body.contentLength gives me the size -1 at all times

I/Upload Task: Uploaded bytes1 -1
I/Upload Task: Uploaded bytes1 -1
I/Upload Task: Uploaded bytes2 -1
I/Upload Executor: 0
I/Upload Task: Uploaded bytes2 -1

### AWS Kotlin SDK version used

0.21.1-beta

### Platform (JVM/JS/Native)

Native Android

### Operating System and version

Android 11

**Comment by ianbotsf** [comment]
Tracking discussion in #490.
