### ISSUE TITLE
Unable to generate SDK code

### ISSUE THREAD

**Issue by tkhill-AWS** [awslabs/aws-sdk-kotlin#931]
### Describe the bug

If I follow the instructions to [Generate an AWS SDK](https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/generate-sdk.md#generate-an-aws-sdk) in `docs/generate-sdk.md`, I consistently get errors.

### Expected behavior

Build part of the SDK -- at least the DynamoDB module

### Current behavior

I consistently get an error when I run:
> .`/gradlew -Paws.services=+dynamodb :codegen:sdk:bootstrap`

per instructions.

### Errors
> * What went wrong:
Project with path ':aws-runtime:protocols:aws-json-protocols' could not be found in project ':services:accessanalyzer'.

Full terminal output:
```
b0be835864fc :: ~/IdeaProjects/aws-sdk-kotlin ‹main› » ./gradlew -Paws.services=+dynamodb :codegen:sdk:bootstrap
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Including build '/Users/tkhill/IdeaProjects/smithy-kotlin'

> Configure project :smithy-kotlin:tests:benchmarks:serde-benchmarks
(scanned and found a Smithy CLI version 1.29.0. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Configure project :smithy-kotlin:tests:codegen:paginator-tests
(scanned and found a Smithy CLI version 1.31.0. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Configure project :smithy-kotlin:tests:codegen:waiter-tests
(scanned and found a Smithy CLI version 1.31.0. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Task :sdk-plugins:compileKotlin
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

> Configure project :aws-runtime:aws-config
(using explicitly configured Smithy CLI)
Disabling project ':aws-runtime:aws-config' task 'jar' because it conflicts with Kotlin JAR tasks
added /Users/tkhill/IdeaProjects/aws-sdk-kotlin/aws-runtime/aws-config/build/smithyprojections/aws-config/sso-credentials-provider/kotlin-codegen/src/main/kotlin to common sourceSet
added /Users/tkhill/IdeaProjects/aws-sdk-kotlin/aws-runtime/aws-config/build/smithyprojections/aws-config/sso-oidc-provider/kotlin-codegen/src/main/kotlin to common sourceSet
added /Users/tkhill/IdeaProjects/aws-sdk-kotlin/aws-runtime/aws-config/build/smithyprojections/aws-config/sts-credentials-provider/kotlin-codegen/src/main/kotlin to common sourceSet

> Configure project :codegen:protocol-tests
(using explicitly configured Smithy CLI)

> Configure project :codegen:sdk
(using explicitly configured Smithy CLI)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tkhill/IdeaProjects/aws-sdk-kotlin/services/accessanalyzer/build.gradle.kts' line: 11

* What went wrong:
Project with path ':aws-runtime:protocols:aws-json-protocols' could not be found in project ':services:accessanalyzer'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
5 actionable tasks: 1 executed, 4 up-to-date
b0be835864fc :: ~/IdeaProjects/aws-sdk-kotlin ‹main› »  
```

### Steps to Reproduce

Follow instructions: https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/generate-sdk.md#generate-an-aws-sdk

### Possible Solution

Something else needs to be build first. If so add those instructions to the documentation for building the SDK.

### Context

I wanted to look at generated SDK code for the URL presigning changes that where yet published to dokka.

### AWS Kotlin SDK version used

0.25.0-beta

### Platform (JVM/JS/Native)

Gradle 8.1.1 / openjdk 11.0.19 2023-04-18 LTS

### Operating System and version

MacOS Ventura 13.4

**Comment by ianbotsf** [comment]
I'm unable to reproduce this. On a fresh checkout of **aws-sdk-kotlin**, I'm able to bootstrap and build the DynamoDB service client successfully.

Your logs indicate Gradle is trying to build the **accessanalyzer** module, which is a different service client unrelated to DynamoDB. It shouldn't have been created by the bootstrap command if the `-Paws.services=+dynamodb` argument was present. Can you try running `git clean -dfx services/` to erase any accidentally-bootstrapped clients and try boostrapping again? If that fails, can you try checking out a clean copy of the **aws-sdk-kotlin** source code?
