### ISSUE TITLE
Question Is the AnonymousCredentialsProvider from the AWS SDK for JAVA now supported in the AWS SDK for Kotlin?

### ISSUE THREAD

**Issue by hansoon1** [awslabs/aws-sdk-kotlin#942]
### Describe the issue

Hello,

I'm trying to create a user-level application to access Amazon WorkDocs in the Android environment.

Using a link below, I can log in and get the access token.

GET https://auth.amazonworkdocs.com/oauth?app_id=my-app-id&auth_type=ImplicitGrant&redirect_uri=https://myapp.com/callback&scopes=workdocs.content.read&state=xyz
( https://docs.aws.amazon.com/workdocs/latest/developerguide/wd-auth-user.html )

First I tried using the AWS SDK for Java, it worked in the console. I was able to get an instance of WorkDocsClient using AnonymousCredentilasProvider.

    AwsCredentialsProvider credentials = AnonymousCredentialsProvider.create();
    WorkDocsClient workDocsClient = WorkDocsClient.builder()
            .region(region)
            .credentialsProvider(credentials).build();
However, this code doesn't work in Android environments due to a runtime exception.

I have been told that this Java SDK is not built for Android, and to use AWS SDK for Kotlin in an Android environment.

My question is, is there an equivalent in the Kotlin SDK to "AnonymousCredentialsProvider" in the JAVA SDK?

I've been looking, but haven't found any hints or code on this. 

### Steps to Reproduce

N/A

### Current behavior

N/A

### AWS Kotlin SDK version used

0.25.0-beta

### Platform (JVM/JS/Native)

Android

### Operating System and version

Android

**Comment by aajtodd** [comment]
> My question is, is there an equivalent in the Kotlin SDK to "AnonymousCredentialsProvider" in the JAVA SDK?

There isn't but if you look at the Java SDK implementation it's just a very simple [type](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsBasicCredentials.java#L46).


I'm not entirely familiar with workdocs and what this use case is that doesn't require credentials. Depending on what you are trying to do you can either give dummy credentials or override the auth scheme to not sign requests using sigv4:

## Option 1: Use dummy credentials

```kotlin
    WorkDocsClient.fromEnvironment{
        credentialsProvider = object : CredentialsProvider {
            override suspend fun resolve(attributes: Attributes): Credentials {
                return Credentials("", "")
            }
        }
    }.use { workdocs ->
        workdocs.describeRootFolders { ... }
    }
```

## Option 2: Override Sigv4 auth scheme to not sign requests

```kotlin
import aws.smithy.kotlin.runtime.auth.AuthSchemeId
import aws.smithy.kotlin.runtime.auth.awscredentials.Credentials
import aws.smithy.kotlin.runtime.auth.awscredentials.CredentialsProvider
import aws.smithy.kotlin.runtime.http.auth.AnonymousHttpSigner
import aws.smithy.kotlin.runtime.http.auth.AnonymousIdentityProvider
import aws.smithy.kotlin.runtime.http.auth.HttpAuthScheme
import aws.smithy.kotlin.runtime.http.auth.HttpSigner
import aws.smithy.kotlin.runtime.identity.IdentityProvider
import aws.smithy.kotlin.runtime.identity.IdentityProviderConfig
import aws.smithy.kotlin.runtime.util.Attributes

...

 val customAuthScheme = object : HttpAuthScheme {
        override val schemeId: AuthSchemeId = AuthSchemeId.AwsSigV4
        override fun identityProvider(identityProviderConfig: IdentityProviderConfig): IdentityProvider = AnonymousIdentityProvider
        override val signer: HttpSigner = AnonymousHttpSigner
    }


    WorkDocsClient.fromEnvironment{
        authSchemes = listOf(customAuthScheme)
    }.use { workdocs ->
        workdocs.describeRootFolders { ... }
    }
```

----

NOTE: These are slightly more advanced options
