### ISSUE TITLE
Fix typo in 's3.getObjet(req)' API reference docs

### ISSUE THREAD

**Issue by tkhill-AWS** [awslabs/aws-sdk-kotlin#994]
### Describe the issue

There is a typo in the [second snippet on the opening S3 API Reference page](https://sdk.amazonaws.com/kotlin/api/latest/s3/index.html).
It reads `s3.getObjet(req)` instead of `s3.getObject(req)`.

### Links

https://sdk.amazonaws.com/kotlin/api/latest/s3/index.html

**Comment by lauzadis** [comment]
Closed by #995. Thanks!
